### ISSUE TITLE
Feature request: Support Thermostat-Devices

### ISSUE THREAD

**Issue by xCite1986** [michbeck100/pimatic-echo#1]
a nice feature would be to control max. or other thermostat devices by 
"Alexa, set Heating control in Livingroom to 21 degrees"
"Alexa, turn Heating control in Livingroom to eco mode"
"Alexa, turn Heating control in Livingroom off"

**Comment by michbeck100** [comment]
This is partly realized with #29. Note that the commands for setting the temperature are the same as with dimming the light. But more commands are not possible for the moment. This would require a smart home skill.
