### ISSUE TITLE
multiple word for one device

### ISSUE THREAD

**Issue by n3roGit** [michbeck100/pimatic-echo#10]
i wold be great to define multiple words for one device because the naming in pimatic and whats alexa understands is not the same.

"zbox" needs to be renamed to "z box". 
alexa dont understand "eck lampen". for alexa its "deckenlampen" :D

**Comment by michbeck100** [comment]
If i understand you correctly, you want to rename the pimatic device from Alexa's point of view?
This is possible since 0.0.4. You can also use white spaces in the name. 

The Amazon documentation says: 

>  The name used by the customer to identify the device. This value cannot exceed 128 characters and should not contain special characters or punctuation.

**Comment by michbeck100** [comment]
0.0.5 adds support for additional names. See README.md for details
