### ISSUE TITLE
more than one button device

### ISSUE THREAD

**Issue by n3roGit** [michbeck100/pimatic-echo#11]
at the moment only the first pimatic button works and the trigger/exclude function is global too.

but this is not very important at the moment.

**Comment by thexperiments** [comment]
I just implemented this for the HAP plugin. 
Maybe we can use the same approach here?

**Comment by n3roGit** [comment]
this feature request is very old. i hope this feature come true

**Comment by michbeck100** [comment]
implemented with https://github.com/michbeck100/pimatic-echo/commit/5a6c8a07ebd4da2e15e778164f4e14c70593abaa
