### ISSUE TITLE
pimatic-shellswitch doesnt work

### ISSUE THREAD

**Issue by scobby** [michbeck100/pimatic-echo#12]
Hello,

the shellswitch devices are not recognized from Echo. They even dont get the echo configuration on device configuration.

**Comment by scobby** [comment]
@michbeck100 can you fix this? this is important to me. Half of my Devices are ShellSwitches ;-)

**Comment by michbeck100** [comment]
That's strange, actually a ShellSwitch should work out of the box. Could you post the configuration part of one of your switches?

**Comment by scobby** [comment]
{
      "onCommand": "wakeonlan.sh XX:XX:XX:XX:XX wakeup",
      "offCommand": "wakeonlan.sh saturn ruhezustand",
      "getStateCommand": "wakeonlan.sh saturn status",
      "interval": 1000,
      "id": "saturn",
      "name": "saturn",
      "class": "ShellSwitch",
      "hap": {}
    },

And DummySwitch look like this:


      "id": "esstisch-szene",
      "name": "Esstisch Szene",
      "class": "DummySwitch",
      "hap": {},
      "echo": {}
    },


if i add  "echo": {}, pimatic complains about that he dont know "echo"

**Comment by scobby** [comment]
i have to correct me, they work somehow, but the configuration "echo" dont work. And i have to Push the "detect new devices" button nearly 100x times to get all Devices in Alexa App

**Comment by michbeck100** [comment]
Please make sure you are using the latest version of pimatic-echo. Like pimatic-hap, the latest update fixes the warnings about the empty echo configuration.
I will try your configuration on my dev system. Where can i get your wakeonlan.sh script? If its open source i would like to try it, as i can only wake up my devices ;-)

**Comment by michbeck100** [comment]
I've added your configuration to my test system using the latest version of pimatic-hap (0.0.5) and there are no problems at all. I get no error message about the echo configuration at all. Please make sure to use the latest version, too. If not sure just delete the pimatic-echo folder from node_modules in your pimatic installation.
