### ISSUE TITLE
Fix device limit

### ISSUE THREAD

**Issue by michbeck100** [michbeck100/pimatic-echo#14]
It seems that there is a limit for the devices that echo supports. One option would be to create multiple upnp listeners.

**Comment by leader21** [comment]
depending on the qty. of the device limit, what about enabling only those devices that you want to control with echo, so making the exclusion a default option for the time being.
i am having a lot of switches and buttons devices but i need only several of these to be controlled by voice.

would be an overkill to have a list where you can select devices via checkboxes to make it user friendlyer i guess 😅

**Comment by t1m02k16** [comment]
But: The Limit Must be very high! Alexa found 21 devices! But i had to press "search" i think 20 Times... Little by little were all recognized. The devices at the end but not

**Comment by thexperiments** [comment]
I am facing the same problem for some time now. It looks like it detects 16 devices in a go. At least if I discover via voice I get this feedback. Over time all devices appear in the echo app. I guess they are rescanning all the time and if this is done often after some time each device was randomly within these 16 devices. I had over 60 devices working but the big problem is that if I change anything or add a new device I have to wait a week and hope that it appears. 

Would be really great if we could solve this.

**Comment by michbeck100** [comment]
According to https://developers.meethue.com/comment/245#comment-245 the device limit of a hue bridge is 50 (actually the hard limit seems to be 63). Alexa also takes this into account and doesn't allow more devices. I've added a counter and won't allow more than 50 devices. Otherwise Alexa will find no devices at all. With #18 there will be a blacklist, which should solve this problem.
