### ISSUE TITLE
pimatic-echo crashes PS4

### ISSUE THREAD

**Issue by mwittig** [michbeck100/pimatic-echo#17]
See the follwoing thread for details. Presumably it is caused by the UPnP messaging.

https://forum.pimatic.org/topic/2926/pimatic-echo-crashes-ps4

**Comment by station7** [comment]
Please feel free to contact me, if you need any logs or debug information (ArthurDent in the pimatic-forum)

**Comment by michbeck100** [comment]
@station7 I would like to move the analyzation to this issue. So please enable debug output as described here: https://github.com/michbeck100/pimatic-echo/issues/7#issuecomment-269228509 
I would need the output just before your PS4 crashes. There should be the ip address in the log. 

BTW: I do have almost the same setup like you, but have no problems when using the PS4

**Comment by station7** [comment]
Hi michbeck100, many thanks for looking into this. I will provide a log this evening when I am back home. Several people confirmed a comparable setup with a PS4 and pimatic-echo without any problems, but I had two (!) PS4 connected to my home network both crashing at the same moment when I started a game. Possible that this is only an issue for my home network, but I am very curious what the debug logs tell you. So keep me posted!

**Comment by station7** [comment]
I am unable to log, sorry. What am I doing wrong?

> pi@pi:~/pimatic-app$ cd node_modules/pimatic
pi@pi:~/pimatic-app/node_modules/pimatic$ DEBUG=ssdp-server node pimatic.js
21:03:31.254 2017-03-21 Tuesday
21:03:40.775 [pimatic] Starting pimatic version 0.9.38
21:03:42.758 [pimatic] Startup error: Error: PRAGMA synchronous=NORMAL; - SQLITE_IOERR: disk I/O error
21:03:42.758 [pimatic]>    at Error (native)
21:03:42.774 [pimatic] exiting...
pi@pi:~/pimatic-app/node_modules/pimatic

I have that error on two RPies, i.e. I can exclude any DISK I/O errors...

**Comment by station7** [comment]
Okay, next update: The crash of the PS4 does not occur, when I start pimatic manually (so logging the error is not possible), only when pimatic is started with the init-script of pimtic [https://pimatic.org/guide/getting-started/autostarting/](url)

I am running OSMC (and not raspbian) on my Pies - that is the reason, why nobode else has this problem, right?

**Comment by michbeck100** [comment]
Then just try to install pimatic on Raspbian. You can use a spare sd card. Please don't install anything else than pimatic-echo.

**Comment by station7** [comment]
No more crashes with raspbian. Switching the underlying OS from OSMC to raspbian finally solved the problem. Still strange, but many thanks for thoughts and input on this!
