### ISSUE TITLE
Feature request: control color of led-lights

### ISSUE THREAD

**Issue by xCite1986** [michbeck100/pimatic-echo#2]
it will be nice to control the color of led-light and milight-reloaded devices like "alexa. set the color of kitchen leds to yellow"

**Comment by michbeck100** [comment]
This is currently just possible with a custom skill for pimatic. See https://github.com/michbeck100/pimatic-echo/issues/6

**Comment by n3roGit** [comment]
i have done this with some button devices "turn on green light" and a pimatic roule

**Comment by michbeck100** [comment]
Ok, but thats a workaround. Currently Alexa doesn't support color changes natively. This will probably change in the future, since Philips Hue lights are natively supported and i don't think that they will stop at switching and dimming.

**Comment by bastardop** [comment]
@michbeck100 has something change in fact of changing color of Rgb devices with this plugin?
