### ISSUE TITLE
Property "ipAddress" is not a valid property

### ISSUE THREAD

**Issue by tehmilcho** [michbeck100/pimatic-echo#23]
Hi,

since the last update i get the following Error by every Reboot from Pimaitc:

error [pimatic]: Invalid config of pimatic-echo: Property "ipAddress" is not a valid property

Config:
   {
      "ipAddress": "192.168.178.20",
      "plugin": "echo",
      "active": true
    },

have you Removed the Config "ipAddress" ?

**Comment by michbeck100** [comment]
Yes, the config entry is gone since one of the last updates. Please reopen if you have problems with the auto discovery mechanism of the ip address
