### ISSUE TITLE
Request: Support for ShellSwitches

### ISSUE THREAD

**Issue by tehmilcho** [michbeck100/pimatic-echo#24]
Hey,

its possible that you can add support for ShellSwitches? Now the will work but you cant exclude them by the WebGUI. i can i manually add the exclude to the Config?

Thank you!

**Comment by michbeck100** [comment]
They should work OOB. If you can't add it through the GUI, you need to manually add it to your config.json.

**Comment by michbeck100** [comment]
In #26 you wrote that your shell switches are working so guess I can close this issue. Reopen if I’m wrong.
