### ISSUE TITLE
After last update WakeOnLAN Device, Shellswitches and homeduino reports erors, Alexa App Groups cant loaded, Alex switches what see want

### ISSUE THREAD

**Issue by tehmilcho** [michbeck100/pimatic-echo#26]
Hey since,

the last update i get a lot of erros, with the other Version "WakeOnLAN Device, Shellswitches and homeduino" works fine with alexa, now i must in the config and set all switches to "true" agian, and i get now a lot of errors.

In the Alexa App loads my groups anymore and if say to alexa see should activat a group see is switches not the correct things....

error [pimatic]: Invalid config of device "hombot": Property "echo" is not a valid property
20:33:58error [pimatic]: Invalid config of device "service-z-way-server": Property "echo" is not a valid property
20:33:57error [pimatic]: Invalid config of device "switch_brennen_c": Property "echo" is not a valid property
20:33:57error [pimatic]: Invalid config of device "switch_brennen_b": Property "echo" is not a valid property
20:33:57error [pimatic]: Invalid config of device "switch_brennen_a": Property "echo" is not a valid property
20:33:57error [pimatic]: Invalid config of device "Wohnzimmer_decken_lampe": Property "echo" is not a valid property
20:33:57error [pimatic]: Invalid config of device "telegram-bot": Property "echo" is not a valid property
20:33:56error [pimatic]: Invalid config of device "Switch": Property "echo" is not a valid property
20:33:56error [pimatic]: Invalid config of device "Schlafzimmer_switch_2": Property "echo" is not a valid property
20:33:56error [pimatic]: Invalid config of device "Schlafzimmer_switch_1": Property "echo" is not a valid property
20:33:56error [pimatic]: Invalid config of device "wol_2": Property "echo" is not a valid property
20:33:56error [pimatic]: Invalid config of device "wol_1": Property "echo" is not a valid property
20:33:56error [pimatic]: Invalid config of device "Wohnzimmer_Switch_3": Property "echo" is not a valid property
20:33:55error [pimatic]: Invalid config of device "Wohnzimmer_switch_1": Property "echo" is not a valid property
20:33:55error [pimatic]: Invalid config of device "Wohnzimmer_switch_2": Property "echo" is not a valid property

**Comment by michbeck100** [comment]
Since the last update you must explicitly activate the devices. Please make sure that you set the active flag in the echo config to true for each device that you want to switch with Alexa. Maybe some of the devices in your Alexa groups are not active after the update.

**Comment by tehmilcho** [comment]
Okay i had now delete all my device from the Alexa app and searched them again then i can open "groups" in the alexa app, i setup all new and it works. 

But is there my WakeOnLan Device will now show as "Wakeup" and not as my "devicename". And i get every reboot of pimatic that errors. 

The most of my Devices had already the "echo" property but wars on "false" after the update, i cant change it via Webgui, so i had to change it all in the Config. =(

**Comment by michbeck100** [comment]
The WakeOnLan Device is Buttonsdevice. With the last update more than just the first button is supported (see #11). Therefor it will use the name of each button for Alexa.
Actually you should not see these “errors” anymore (actually they are just warnings and can be ignored). 
Furthermore you should be able to edit the config in the web gui. At least I can edit everything without any problems.

**Comment by tehmilcho** [comment]
"protocols": [
        {
          "name": "switch6",
          "options": {
            "systemcode": 31,
            "programcode": 2
          },
          "send": true,
          "receive": true
        }
      ],
      "id": "Wohnzimmer_switch_1",
      "name": "Sofa",
      "class": "HomeduinoRFSwitch",
      "echo": {
        "active": true
      }

If you not get the Errors is there something wrong mit my device config? i never changed them via the config file, i do it every time over the Webgui....

**Comment by tehmilcho** [comment]
Also if i create a new homeduino-Device, i cant see the Alexa Options in the Device and get after a reboot the Error. And i changed nothing on the Config of this device.

[pimatic]: Invalid config of device "test": Property "echo" is not a valid property

Config of the new Device, created by Pimatic:
    {
      "protocols": [],
      "id": "test",
      "name": "test",
      "class": "HomeduinoRFSwitch",
      "echo": {
        "active": false
      }
    }
  ],

**Comment by michbeck100** [comment]
This happens for me if I deactivate the pimatic-echo plugin completely. But I guess this is not the case for you ;-). Anyway, you can ignore these messages. They come from pimatic core, because it thinks this device uses a config that is not supported. Pimatic-echo extends the config of every device, but this isn’t fully supported by pimatic. This would need a bigger change on pimatic itself. For now it works, but with this message.

**Comment by michbeck100** [comment]
Just make sure you are using the latest pimatic (plugins) version. I can’t say why you don’t see the config in the GUI.

**Comment by michbeck100** [comment]
You could ask in the pimatic forum if you aren’t alone with this.

**Comment by tehmilcho** [comment]
hey what i not understand... it works fine with Dummyswitches (No errors, WebGUI - Echo Options in the Device) its only with the Plugins:
-Zwave
-Shellswitch
-Homduino
-WakeOnLAN
-sunrise
-telegram

i check my Dummys in the Config if there something different but there is nothing, 

i have the lasted version of pimatic and all plugins, i tryed to reinstall the Echo Plugin without success, without the active echo-plugin i get 78x the not vaild Property, with active echo-plugin only 24x. 

I open a Post also in the Pimatic forum
https://forum.pimatic.org/topic/3284/how-to-get-echo-to-vaild-property

**Comment by tehmilcho** [comment]
Solved by putting the echo-plugin as first plugin in the config. (if you get missing property "echo" after this just reboot pimatic again)
