### ISSUE TITLE
Extend hue protocol

### ISSUE THREAD

**Issue by frotzamuta** [michbeck100/pimatic-echo#27]
The implementation of the hue protocol is very limited. Alexa/echo works fine but other devices (in my case a harmony hub) do not work.
I know that the main intention of this plugin is to make devices available to echo, but I think an extension to other products would not harm.

I tested a bit and I think the main problem currently is, that there is no possibility to register new users.
This project may help to implement the missing parts: https://github.com/peterkaminski/kingfish
New users are requested by calling the url 
`[ip]:[port]/api/[something]`
and the response should look like this (the name may differ ;)):
```
[
    {
        "success": {
            "username": "6e4bcbc7bc5843b88d876012b6868dfb"
        }
    }
]
```
All following requests to the "bridge" will look like
`[ip]:[port]/api/6e4bcbc7bc5843b88d876012b6868dfb/...`

Maybe it would also make sense to create it as a new plugin "hue-sim" or something similar.

Kind regards,
Daniel

**Comment by michbeck100** [comment]
Sorry, but I will only implement the parts of the protocol that are needed for Alexa. BTW: With #28 the api for new users was added.
