### ISSUE TITLE
Button Device does not respond

### ISSUE THREAD

**Issue by mathiaslehmann** [michbeck100/pimatic-echo#32]
Hello, I upgraded to version 0.4.2 today. Unfortunately my button device does not work anymore. In Alexa App appears “Device does not respond”. In version 0.4.1 it worked great.

**Comment by n3roGit** [comment]
Same here! I have removed all devices in alexa but can't find the buttons anymore

**Comment by mathiaslehmann** [comment]
The buttons are still found in my environment. Only the operation does not work anymore. Here is an example of my buttons for a roller shutter.

{
      "id": "roll1wohnzimmer",
      "name": "Rollo 1 Wohnzimmer",
      "class": "HomeduinoRFButtonsDevice",
      "buttons": [
        {
          "id": "roll1-up",
          "text": "1 auf",
          "protocols": [
            {
              "name": "shutter3",
              "options": {
                "id": "128457090",
                "channel": "1",
                "command": "up"
              },
              "rfrepeats": 2
            }
          ]
        },
        {
          "id": "roll1-stop",
          "text": "1 stop",
          "protocols": [
            {
              "name": "shutter3",
              "options": {
                "id": "128457090",
                "channel": "1",
                "command": "stop"
              },
              "rfrepeats": 2
            }
          ]
        },
        {
          "id": "roll1-down",
          "text": "1 ab",
          "protocols": [
            {
              "name": "shutter3",
              "options": {
                "id": "128457090",
                "channel": "1",
                "command": "down"
              },
              "rfrepeats": 2
            }
          ]
        }
      ],
      "echo": {
        "additionalNames": [],
        "active": true,
        "hueType": "Switch"
      }
    },

**Comment by mathiaslehmann** [comment]
It works great again in version 0.4.3. Thank you

**Comment by n3roGit** [comment]
i still cant find my button device:

{
      "buttons": [
        {
          "id": "chill",
          "text": "Gemütlich"
        },
        {
          "id": "bright",
          "text": "Hell"
        },
        {
          "id": "dark",
          "text": "Dunkel"
        }
      ],
      "echo": {
        "additionalNames": [],
        "active": true,
        "hueType": "Switch"
      },
      "id": "szenen",
      "name": "Szenen",
      "class": "ButtonsDevice"
    }

**Comment by michbeck100** [comment]
Please try to remove the devices from Alexa again before and make sure you are using version 0.4.3.

**Comment by michbeck100** [comment]
@n3roGit Oh and please remove the hueType config property. This was a temporal property from another fork of pimatic-echo, which never made it to my repo.

**Comment by n3roGit** [comment]
Hi =)

i have done both but still cant find device :(

**Comment by michbeck100** [comment]
@n3roGit Do you have the same problems as in #16 ?

**Comment by n3roGit** [comment]
I don't think so. I proceeded as follows.

pimatic update
restart
delete all devices in alexa
search for new devices in alexa

I'll find some devices. but not the buttons

**Comment by michbeck100** [comment]
What type of devices does your echo find?

**Comment by n3roGit** [comment]
WeMo and Lux Light devices. But no WeMo(Button) Device anymore

**Comment by michbeck100** [comment]
Are you also using a new Echo 2? This ticket was initially about buttons that can be found but cannot be switched anymore.

**Comment by mathiaslehmann** [comment]
Have just tested times.

All devices deleted in Alexa. Then search for devices. At first only all devices of the type "Lux Light" are found. New search started, now devices of the type "WeMo Switch" are added in the device list. But not all. I have two missing. Had to re-search several times in the Alexa until all devices were there.

I tried again. All devices deleted. Search for new devices in the Alexa. Now some "WeMo Switch" devices are found. But not all. Search again, no new devices will be found. After a short wait, new search. All devices of the type "Lux Light" come to it. I then repeated it until all devices were in the list.

Have an Echo Dot 2nd generation. In the device configurations in Pimatic I have everywhere removed the parameter "hueType".

**Comment by mathiaslehmann** [comment]
I have just noticed that always some devices in the list in Alexa are marked as offline. But they all work wonderfully.

Am logged in at "https://alexa.amazon.de/" on Echo.

![image](https://user-images.githubusercontent.com/16978467/32787263-67b2623e-c956-11e7-8bd6-4d38fd31bebc.png)

**Comment by michbeck100** [comment]
Thats just the WeMo switches. I guess these are all ButtonsDevices?

**Comment by michbeck100** [comment]
Looks like i have to revert to version 0.4.1 for now.

**Comment by n3roGit** [comment]
i have the same like mathiaslehmann! but after multiple searches my wanted button device is still noch there

**Comment by michbeck100** [comment]
Please try the version 0.4.4

**Comment by mathiaslehmann** [comment]
In version 0.4.4. the behavior of the search is the same as in 0.4.3.

In principle, everything works great. There are only the difficulties in the search. Once you have found all the devices, they also work great.

**Comment by michbeck100** [comment]
@mathiaslehmann So for you you the search for buttons is working (at least sometimes)?

**Comment by mathiaslehmann** [comment]
Ich schreibe jetzt mal auf Deutsch, ich hoffe das ist okay.
Die Suche funktioniert soweit. Nur werden nicht alle Geräte gefunden wenn die Suche einmal ausgeführt wird. Mal fehlen die Knöpfe (WeMo Switch), mal die Dimmer (Lux Light). Mir kommt es so vor, dass es davon abhängig ist zu welchem Zeitpunkt gesucht wird. Die mehrfache Suche sorgt am Ende dafür das alle Geräte zur Verfügung stehen. Hat man dann mal alle Geräte in Alexa zusammen, funktionieren alle auch wunderbar und können per Sprachbefehl gesteuert werden. Das Problem ist in der Version 0.4.4 geblieben.

**Comment by michbeck100** [comment]
The next release will switch back to hue lights emulation only. It seems that WeMo switches are not working properly

**Comment by michbeck100** [comment]
I'm closing this for now. If there are still any problems with the next release, please reopen
