### ISSUE TITLE
duplicated names

### ISSUE THREAD

**Issue by n3roGit** [michbeck100/pimatic-echo#33]
I have the following problem.

I use the same display name for several devices. e. g."wohnzimmer".

This means that alexa has duplicated names and can no longer switch some devices.

is it possible to set the default name for alexa in the device settings independent of the display name?

https://www.pic-upload.de/view-34292803/pimatic.png.html

**Comment by michbeck100** [comment]
Please use the name property the device configuration: https://github.com/michbeck100/pimatic-echo/blob/master/README.md#configuration

**Comment by michbeck100** [comment]
Note that this doesn't work for ButtonsDevice

**Comment by n3roGit** [comment]
You are FAST :D i will try it!

Give me a sec

**Comment by n3roGit** [comment]
ah okay you mean the additionalNames feature. 

I only want to use the additionalNames.
The display name should be excluded for alexa. is there any way to do this?

**Comment by michbeck100** [comment]
No i'm talking about the name:
```json
"devices": [
  {
    "id": "switch",
    "class": "DummySwitch",
    "name": "Switch",
    "echo": {
      **"name": "EchoSwitch",**
      "additionalNames": ["AnotherNameForMyEchoSwitch", "YetAnotherName"],
      "active": true,
      "debug": false,
      "comfyTemp": 21,
      "ecoTemp": 17
    }
  }
]

```

**Comment by n3roGit** [comment]
perfect!!!!!! THX

**Comment by n3roGit** [comment]
why its greyed out?

https://www.pic-upload.de/view-34293081/pimatic.png.html

**Comment by n3roGit** [comment]
OK it works after editing the config directly. THX

**Comment by michbeck100** [comment]
don't know why it's not editable. This has to do with the mobile frontend i guess. Closing this issue.
