### ISSUE TITLE
echo plus support?

### ISSUE THREAD

**Issue by RogerHartmann** [michbeck100/pimatic-echo#34]
Hello all,

i have not been successful to find pimatic devices with the new Echo Plus. Do not have another echo, so I cannot check if the workaround mentioned before to find pimatic with an older echo works.
I am happy to provide protocols, etc. to help implementation.
thanks!
Roger

PS: really interesting would be also to control the devices paired to the echo plus. but that is another topic :-D

**Comment by michbeck100** [comment]
Please try to set the port from 9876 to 80 in the config

**Comment by michbeck100** [comment]
I'm closing this, as people are reporting that port 80 works. This might get the default port someday.

**Comment by RogerHartmann** [comment]
Thanks a lot! I will check when I am back home
