### ISSUE TITLE
How to have switches not as lights?

### ISSUE THREAD

**Issue by RogerHartmann** [michbeck100/pimatic-echo#36]
Hallo Michael @michbeck100
This is more a question but an issue. Not sure how else to ask:
Is it possible to classify a switch not as a light?
My use case: I have an Espresso machine connected to a WiFi socket. I can control that via Alexa. 
But when I tell her „all lights on“, she also switches on the espresso machine, what I do not want. 
Any way?
Remark: I only have the switches connected via hue emulation. Would that differ if they are connected via WeMo emulation? If so, how would I do this, Alexa shows only the hue devices...
Thanks!
Roger

**Comment by michbeck100** [comment]
I've removed the WeMo emulation, as this was requested on the one hand and didn't work reliable on the other hand. So, the answer is no, this will not be part of pimatic-echo in the next future. May be i will add it again some day. I'm leaving this issue open.

**Comment by RogerHartmann** [comment]
Thanks @michbeck100 for this quick answer. I will continue watching this issue

**Comment by RogerHartmann** [comment]
@michbeck100: an idea that came to my mind: a checkbox like "only switch individually". Then, if the echo plugin detects that multiple devices are switched in a very short time (e.g. <1s) then this device' command is ignored. Will try to implement this with a rule where I check if also "honey pot switch" is activated. 
What do you think?

**Comment by michbeck100** [comment]
I'm not sure what this has to do with this issue?

**Comment by RogerHartmann** [comment]
my use case is that I have a WiFi socket for the coffee machine. And that must not be switched on/off with the command for all lights. Therefore I need a workaround to exclude the socket. I implemented this with a 2 dummy dimmers in pimatic and a rule that checks that not both were activated together. Only then, the "real" WiFi socket is turned on.
Having an option in echo would make this easier.

**Comment by michbeck100** [comment]
As I won't implement this in pimatic-echo, but rather in the upcoming pimatic skill, I'm closing this
