### ISSUE TITLE
since echo 0.4.7 -  no device found

### ISSUE THREAD

**Issue by n3roGit** [michbeck100/pimatic-echo#37]
since the version 0.4.7 i cant find any device in alexa :(

**Comment by michbeck100** [comment]
Please post your plugin config and one device config here

**Comment by n3roGit** [comment]
{
      "plugin": "echo",
      "ipAddress": "127.0.0.1",
      "active": true,
      "debug": false,
      "comfyTemp": 21,
      "ecoTemp": 18
    },


    {
      "id": "rfdimmer01",
      "name": "kleine Stehlampe",
      "class": "HomeduinoRFDimmer",
      "protocols": [
        {
          "name": "dimmer1",
          "options": {
            "id": 1234567,
            "unit": 0
          }
        }
      ],
      "forceSend": true,
      "echo": {
        "active": true
      }
    },
    {
      "id": "rfdimmer01",
      "name": "kleine Stehlampe",
      "class": "HomeduinoRFDimmer",
      "protocols": [
        {
          "name": "dimmer1",
          "options": {
            "id": 234567,
            "unit": 0
          }
        }
      ],
      "forceSend": true,
      "echo": {
        "active": true
      }
    },

**Comment by michbeck100** [comment]
The ipAddress can't be 127.0.0.1. If you have a standard system with just one ip address, you can remove this setting completely. pimatic-echo will try to determine this automatically. If this doesn't work you can set the address manually. But it must be the ip address of your system, as its used to tell Alexa where to find the devices.

**Comment by n3roGit** [comment]
i have done it. but still the same after restart of pimatic

**Comment by n3roGit** [comment]
info [pimatic-echo]: started hue emulator on port 9876
12:04:23info [pimatic-echo]: Starting pimatic-echo...
11:08:01info [pimatic-echo]: started hue emulator on port 9876
11:06:28info [pimatic-echo]: Starting pimatic-echo...
2017-11-22 09:01:08info [pimatic-echo]: started hue emulator on port 9876
08:59:23info [pimatic-echo]: Starting pimatic-echo...
08:33:20info [pimatic-echo]: started hue emulator on port 9876
08:31:42info [pimatic-echo]: Starting pimatic-echo...
2017-11-20 11:01:46info [pimatic-echo]: started hue emulator on port 9876
11:00:03info [pimatic-echo]: Starting pimatic-echo...
2017-11-18 09:23:13info [pimatic-echo]: started hue emulator on port 9876
09:21:37info [pimatic-echo]: Starting pimatic-echo...
2017-11-17 22:18:29info [pimatic-echo]: started hue emulator on port 9876
22:16:49info [pimatic-echo]: Starting pimatic-echo...
2017-11-16 22:25:42info [pimatic-echo]: started hue emulator on port 9876
22:24:06info [pimatic-echo]: Starting pimatic-echo...

**Comment by michbeck100** [comment]
Are you using a new echo?

**Comment by n3roGit** [comment]
I use the echo Dot gen2

**Comment by michbeck100** [comment]
Then set the trace and debug config on the plugin to true and see what the log says

**Comment by n3roGit** [comment]
debug [pimatic-echo]: Headers: {
  "host": "192.168.1.13:9876",
  "accept": "*/*"
}
13:23:32debug [pimatic-echo]: Request to /api/t6QKkj8MZQa4BnGe4c2E1GCCOw4lGAjxy2EtN7iJ/groups/0
13:23:32debug [pimatic-echo]: Headers: {
  "host": "192.168.1.13:9876",
  "accept": "*/*"
}
13:23:32debug [pimatic-echo]: Request to /api/t6QKkj8MZQa4BnGe4c2E1GCCOw4lGAjxy2EtN7iJ/groups/0
13:23:32debug [pimatic-echo]: Headers: {
  "host": "192.168.1.13:9876",
  "accept": "*/*"
}
13:23:32debug [pimatic-echo]: Request to /api/t6QKkj8MZQa4BnGe4c2E1GCCOw4lGAjxy2EtN7iJ/groups/0
13:23:32debug [pimatic-echo]: Headers: {
  "host": "192.168.1.13:9876",
  "accept": "*/*"
}
13:23:32debug [pimatic-echo]: Request to /api/t6QKkj8MZQa4BnGe4c2E1GCCOw4lGAjxy2EtN7iJ/groups/0
13:02:01info [pimatic-echo]: started hue emulator on port 9876
13:00:21info [pimatic-echo]: Starting pimatic-echo...
12:06:07info [pimatic-echo]: started hue emulator on port 9876

**Comment by michbeck100** [comment]
A log while running the device scan would be good.

**Comment by n3roGit** [comment]
This was a log while scanning :)

**Comment by n3roGit** [comment]
debug [pimatic-echo]: Headers: {
  "host": "192.168.1.13:9876",
  "accept": "*/*"
}
15:36:09debug [pimatic-echo]: Request to /api/t6QKkj8MZQa4BnGe4c2E1GCCOw4lGAjxy2EtN7iJ/groups/0
15:36:09debug [pimatic-echo]: Headers: {
  "host": "192.168.1.13:9876",
  "accept": "*/*"
}
15:36:09debug [pimatic-echo]: Request to /api/t6QKkj8MZQa4BnGe4c2E1GCCOw4lGAjxy2EtN7iJ/groups/0
15:36:09debug [pimatic-echo]: Headers: {
  "host": "192.168.1.13:9876",
  "accept": "*/*"
}
15:36:09debug [pimatic-echo]: Request to /api/t6QKkj8MZQa4BnGe4c2E1GCCOw4lGAjxy2EtN7iJ/groups/0
15:36:09debug [pimatic-echo]: Headers: {
  "host": "192.168.1.13:9876",
  "accept": "*/*"
}
15:36:09debug [pimatic-echo]: Request to /api/t6QKkj8MZQa4BnGe4c2E1GCCOw4lGAjxy2EtN7iJ/groups/0

**Comment by michbeck100** [comment]
Then Alexa doesn't find pimatic. Did you set the trace option in the plugin to true?

**Comment by n3roGit** [comment]
yes!

**Comment by n3roGit** [comment]
{
      "plugin": "echo",
      "active": true,
      "debug": true,
      "comfyTemp": 21,
      "ecoTemp": 18,
      "trace": true
    },

**Comment by n3roGit** [comment]
with the version before it works great

**Comment by michbeck100** [comment]
Do you know what the version before was? Was it 0.4.6? Or some version before? Because there were no big changes between 0.4.6 and 0.4.7

**Comment by n3roGit** [comment]
is was 0.4.6

**Comment by michbeck100** [comment]
Could you please try to install version 0.4.6 again and tell if its fixed then?

To install an older release see Method 1 from https://forum.pimatic.org/topic/1114/updated-how-to-install-a-plugin-from-github-using-npm-or-git but use 
```
sudo npm install pimatic-echo@0.4.6 --unsafe-perm
```

**Comment by n3roGit** [comment]
i get this:

root@myserver130:/opt/pimatic-app/node_modules service pimatic stop
root@myserver0:/opt/pimatic-app/node_modules rm -rf pimatic-echo
root@myserver0:/opt/pimatic-app/node_modules npm install pimatic-echo@0.4.6 --unsafe-perm
npm WARN engine pimatic-echo@0.4.6: wanted: {"node":">4.4","npm":">2.15"} (current: {"node":"4.4.7","npm":"2.15.8"})
npm ERR! Linux 4.9.35-v7+
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "pimatic-echo@0.4.6" "--unsafe-perm"
npm ERR! node v4.4.7
npm ERR! npm  v2.15.8
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package pimatic@0.9.42 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer pimatic-amazing-dash-button@0.9.13 wants pimatic@>=0.8.0 <1.0.0
npm ERR! peerinvalid Peer pimatic-calendar@0.8.0 wants pimatic@0.8.*
npm ERR! peerinvalid Peer pimatic-cron@0.8.8 wants pimatic@>=0.8.0 <1.0.0
npm ERR! peerinvalid Peer pimatic-echo@0.4.6 wants pimatic@~0.9.0
npm ERR! peerinvalid Peer pimatic-fritz@0.5.6 wants pimatic@>0.8.91 <1.0.0
npm ERR! peerinvalid Peer pimatic-google-calendar@0.4.1 wants pimatic@>=0.8.0 <1.0.0
npm ERR! peerinvalid Peer pimatic-homeduino@0.9.11 wants pimatic@0.9.*
npm ERR! peerinvalid Peer pimatic-iframe@0.3.1 wants pimatic@>=0.8.0 <1.0.0
npm ERR! peerinvalid Peer pimatic-kodi@0.1.9 wants pimatic@>=0.8.0 <1.0.0
npm ERR! peerinvalid Peer pimatic-led-light@0.9.5 wants pimatic@>=0.9.0 <1.0.0
npm ERR! peerinvalid Peer pimatic-links@0.8.6 wants pimatic@>=0.8.0 <1.0.0
npm ERR! peerinvalid Peer pimatic-location@0.2.5 wants pimatic@>=0.8.0 <1.0.0
npm ERR! peerinvalid Peer pimatic-mail@0.8.6 wants pimatic@>=0.8.0 <1.0.0
npm ERR! peerinvalid Peer pimatic-max@0.9.0 wants pimatic@>=0.8.31 <1.0.0
npm ERR! peerinvalid Peer pimatic-milight-reloaded@0.9.14 wants pimatic@>=0.8.0 <1.0.0
npm ERR! peerinvalid Peer pimatic-mobile-frontend@0.9.12 wants pimatic@0.9.*
npm ERR! peerinvalid Peer pimatic-mqtt@0.9.7 wants pimatic@>=0.9.0 <1.0.0
npm ERR! peerinvalid Peer pimatic-mysensors@0.9.0 wants pimatic@>=0.8.0 <1.0.0
npm ERR! peerinvalid Peer pimatic-netcheck@1.1.0 wants pimatic@0.9.*
npm ERR! peerinvalid Peer pimatic-node-red@1.0.7 wants pimatic@0.9.*
npm ERR! peerinvalid Peer pimatic-openweather@0.9.4 wants pimatic@>=0.8.0 <1.0.0
npm ERR! peerinvalid Peer pimatic-phone@0.9.6 wants pimatic@~0.9.0
npm ERR! peerinvalid Peer pimatic-ping@0.9.5 wants pimatic@>=0.8.0 <1.0.0
npm ERR! peerinvalid Peer pimatic-pushbullet@0.9.0 wants pimatic@>=0.8.0 <1.0.0
npm ERR! peerinvalid Peer pimatic-shell-execute@0.9.11 wants pimatic@0.9.*
npm ERR! peerinvalid Peer pimatic-snmp@0.4.0 wants pimatic@>=0.8.0 <1.0.0
npm ERR! peerinvalid Peer pimatic-sunrise@0.8.7 wants pimatic@>=0.8.0 <1.0.0
npm ERR! peerinvalid Peer pimatic-sysinfo@0.9.4 wants pimatic@0.9.*
npm ERR! peerinvalid Peer pimatic-wakeonlan@0.9.4 wants pimatic@>=0.8.0 <1.0.0
npm ERR! peerinvalid Peer pimatic-z-way@1.4.3 wants pimatic@>=0.8.0 <1.0.0

npm ERR! Please include the following file with any support request:
npm ERR!     /opt/pimatic-app/node_modules/npm-debug.log

**Comment by n3roGit** [comment]
hmm plugin seems to be installed. but still doesnt work...

**Comment by n3roGit** [comment]
Any ideas?

**Comment by michbeck100** [comment]
Not yet, i'm testing this weekend. I hope i can fix most of the known issues. You are not the only one currently.

**Comment by n3roGit** [comment]
Found this on the log:

28error [pimatic-echo]: Error starting hue emulator. Port 80 is not available.
18:08:17error [pimatic-echo]: Error starting hue emulator. Port 80 is not available.


Why Port 80 is default?

**Comment by michbeck100** [comment]
Because the new echoes need this to be on port 80. you can change it back to whatever you want if you don’t have port 80 free

**Comment by n3roGit** [comment]
ah thx ok!

now i have changed my config for testing to this:

    {
      "plugin": "echo",
      "active": true,
      "debug": true,
      "comfyTemp": 21,
      "ecoTemp": 18,
      "trace": true,
      "port": 81,
      "address": "192.168.1.13",
      "mac": "My MAC Address"
    },

And get this in the log?
But still no devices found in alexa.


debug [pimatic-echo]: Headers: {
  "host": "192.168.1.13:81",
  "accept": "*/*"
}
14:32:58debug [pimatic-echo]: GET Request to /api/t6QKkj8MZQa4BnGe4c2E1GCCOw4lGAjxy2EtN7iJ/groups/0
14:32:58debug [pimatic-echo]: Headers: {
  "host": "192.168.1.13:81",
  "accept": "*/*"
}
14:32:58debug [pimatic-echo]: GET Request to /api/t6QKkj8MZQa4BnGe4c2E1GCCOw4lGAjxy2EtN7iJ/groups/0
14:32:57debug [pimatic-echo]: Headers: {
  "host": "192.168.1.13:81",
  "accept": "*/*"
}
14:32:57debug [pimatic-echo]: GET Request to /api/t6QKkj8MZQa4BnGe4c2E1GCCOw4lGAjxy2EtN7iJ/groups/0
14:32:57debug [pimatic-echo]: Headers: {
  "host": "192.168.1.13:81",
  "accept": "*/*"
}
14:32:57debug [pimatic-echo]: GET Request to /api/t6QKkj8MZQa4BnGe4c2E1GCCOw4lGAjxy2EtN7iJ/groups/0
14:32:52debug [pimatic-echo]: Headers: {
  "host": "192.168.1.13:81",
  "accept": "*/*"
}
14:32:52debug [pimatic-echo]: GET Request to /api/t6QKkj8MZQa4BnGe4c2E1GCCOw4lGAjxy2EtN7iJ/lights
14:32:52debug [pimatic-echo]: Headers: {
  "host": "192.168.1.13:81",
  "accept": "*/*"
}

**Comment by n3roGit** [comment]
Do you have any idea what else I can debug?

**Comment by michbeck100** [comment]
No, not at the moment. I'm currently struggling to get the plugin working with both generations of the echo. Once i finished this, i hope this issue is fixed too.

**Comment by n3roGit** [comment]
Perfect! Thx Y!

**Comment by n3roGit** [comment]
After the Upgrade to the new version i have still no devices in alexa but this in the echo log:

error [pimatic-echo]: Error starting hue emulator. Port 80 is not available.

But my config is this:

    {
      "plugin": "echo",
      "active": true,
      "debug": true,
      "comfyTemp": 21,
      "ecoTemp": 18,
      "trace": true,
      "port": 81,
      "pairingEnabled": true
    },

**Comment by n3roGit** [comment]
Sorry! I was mistaken. The error with port 80 is from the past!

However, I still don't find any devices.



debug [pimatic-echo]: Pairing is disabled and user t6QKkj8MZQa4BnGe4c2E1GCCOw4lGAjxy2EtN7iJ was not found
17:34:11debug [pimatic-echo]: Headers: {
  "host": "192.168.1.13:81",
  "accept": "*/*"
}
17:34:11debug [pimatic-echo]: GET Request to /api/t6QKkj8MZQa4BnGe4c2E1GCCOw4lGAjxy2EtN7iJ
17:34:11debug [pimatic-echo]: Request: /api/t6QKkj8MZQa4BnGe4c2E1GCCOw4lGAjxy2EtN7iJ
17:34:11debug [pimatic-echo]: Pairing is disabled and user t6QKkj8MZQa4BnGe4c2E1GCCOw4lGAjxy2EtN7iJ was not found
17:34:11debug [pimatic-echo]: Headers: {
  "host": "192.168.1.13:81",
  "accept": "*/*"
}
17:34:11debug [pimatic-echo]: GET Request to /api/t6QKkj8MZQa4BnGe4c2E1GCCOw4lGAjxy2EtN7iJ
17:34:11debug [pimatic-echo]: Request: /api/t6QKkj8MZQa4BnGe4c2E1GCCOw4lGAjxy2EtN7iJ
17:34:11debug [pimatic-echo]: Pairing is disabled and user t6QKkj8MZQa4BnGe4c2E1GCCOw4lGAjxy2EtN7iJ was not found
17:34:11debug [pimatic-echo]: Headers: {
  "host": "192.168.1.13:81",
  "accept": "*/*"
}
17:34:11debug [pimatic-echo]: GET Request to /api/t6QKkj8MZQa4BnGe4c2E1GCCOw4lGAjxy2EtN7iJ/lights
17:34:11debug [pimatic-echo]: Request: /api/t6QKkj8MZQa4BnGe4c2E1GCCOw4lGAjxy2EtN7iJ/lights
17:34:11debug [pimatic-echo]: Pairing is disabled and user t6QKkj8MZQa4BnGe4c2E1GCCOw4lGAjxy2EtN7iJ was not found
17:34:11debug [pimatic-echo]: Headers: {
  "host": "192.168.1.13:81",
  "accept": "*/*"
}
17:34:11debug [pimatic-echo]: GET Request to /api/t6QKkj8MZQa4BnGe4c2E1GCCOw4lGAjxy2EtN7iJ/lights
17:34:11debug [pimatic-echo]: Request: /api/t6QKkj8MZQa4BnGe4c2E1GCCOw4lGAjxy2EtN7iJ/lights
17:34:11debug [pimatic-echo]: Headers: {
  "host": "192.168.1.13:81",
  "accept": "*/*"
}
17:34:11debug [pimatic-echo]: GET Request to /description.xml
17:34:11debug [pimatic-echo]: Request: /description.xml
17:34:11debug [pimatic-echo]: Headers: {
  "host": "192.168.1.13:81",
  "accept": "*/*"
}
17:34:11debug [pimatic-echo]: GET Request to /description.xml
17:34:11debug [pimatic-echo]: Request: /description.xml
17:34:11debug [pimatic-echo]: complete sending all responses.
17:34:10debug [pimatic-echo]: >> sent response ssdp discovery response: HTTP/1.1 200 OK
HOST: 239.255.255.250:1900
EXT:
CACHE-CONTROL: max-age=100
LOCATION: http://192.168.1.13:81/description.xml
SERVER: FreeRTOS/7.4.2, UPnP/1.0, IpBridge/1.19.0
hue-bridgeid: B827EBFFFE679E6D
ST: uuid: 2f402f80-da50-11e1-9b23-b827eb679e6d
USN: uuid:2f402f80-da50-11e1-9b23-b827eb679e6d::upnp:rootdevice

**Comment by n3roGit** [comment]
Maybe the following is still important.

Pimatic runs on port 8087, the ports 80 and 443 are occupied by nginx.

must port 80 be free for using echo plugin?
Maybe I can then create a rule in nginx or make the port completely free.

**Comment by michbeck100** [comment]
It needs to run on port 80 if you have a new echo or echo plus. For discovery please see https://forum.pimatic.org/topic/2648/pimatic-echo-control-your-pimatic-devices-using-amazon-s-echo/175

**Comment by xCite1986** [comment]
hey...
i'm having the same errors, 

if i search for devices i would get

debug [pimatic-echo]: **Pairing is disabled and user qIW5mAN8DZPsBCxb958Kb2hM8IYl7sq7c4HcyNZY was not found**
20:15:09debug [pimatic-echo]: Headers: {
  "host": "192.168.0.200:81",
  "accept": "*/*"
}
20:15:09debug [pimatic-echo]: GET Request to /api/qIW5mAN8DZPsBCxb958Kb2hM8IYl7sq7c4HcyNZY
20:15:09debug [pimatic-echo]: Request: /api/qIW5mAN8DZPsBCxb958Kb2hM8IYl7sq7c4HcyNZY
20:15:08debug [pimatic-echo]: Pairing is disabled and user qIW5mAN8DZPsBCxb958Kb2hM8IYl7sq7c4HcyNZY was not found
20:15:08debug [pimatic-echo]: Headers: {
  "host": "192.168.0.200:81",
  "accept": "*/*"
}
20:15:08debug [pimatic-echo]: GET Request to /api/qIW5mAN8DZPsBCxb958Kb2hM8IYl7sq7c4HcyNZY
20:15:08debug [pimatic-echo]: Request: /api/qIW5mAN8DZPsBCxb958Kb2hM8IYl7sq7c4HcyNZY
20:15:08debug [pimatic-echo]: Pairing is disabled and user qIW5mAN8DZPsBCxb958Kb2hM8IYl7sq7c4HcyNZY was not found
20:15:08debug [pimatic-echo]: Headers: {
  "host": "192.168.0.200:81",
  "accept": "*/*"
}
20:15:08debug [pimatic-echo]: GET Request to /api/qIW5mAN8DZPsBCxb958Kb2hM8IYl7sq7c4HcyNZY/lights
20:15:08debug [pimatic-echo]: Request: /api/qIW5mAN8DZPsBCxb958Kb2hM8IYl7sq7c4HcyNZY/lights
20:15:08debug [pimatic-echo]: Pairing is disabled and user qIW5mAN8DZPsBCxb958Kb2hM8IYl7sq7c4HcyNZY was not found
20:15:08debug [pimatic-echo]: Headers: {
  "host": "192.168.0.200:81",
  "accept": "*/*"
}
20:15:08debug [pimatic-echo]: GET Request to /api/qIW5mAN8DZPsBCxb958Kb2hM8IYl7sq7c4HcyNZY/lights
20:15:08debug [pimatic-echo]: Request: /api/qIW5mAN8DZPsBCxb958Kb2hM8IYl7sq7c4HcyNZY/lights
20:15:08debug [pimatic-echo]: Headers: {
  "host": "192.168.0.200:81",
  "accept": "*/*"
}
20:15:08debug [pimatic-echo]: GET Request to /description.xml
20:15:08debug [pimatic-echo]: Request: /description.xml
20:15:08debug [pimatic-echo]: Headers: {
  "host": "192.168.0.200:81",
  "accept": "*/*"
}
20:15:08debug [pimatic-echo]: GET Request to /description.xml
20:15:08debug [pimatic-echo]: Request: /description.xml
20:15:08debug [pimatic-echo]: complete sending all responses.


pimatic was running on 80, pimatic-echo on 81

 "plugins": [
    {
      "debug": true,
      "plugin": "echo",
      "active": true,
      "comfyTemp": 20,
      "ecoTemp": 4.5,
      "pairingEnabled": true,
      "port": 81
    }......

**Comment by michbeck100** [comment]
Did you read https://forum.pimatic.org/topic/2648/pimatic-echo-control-your-pimatic-devices-using-amazon-s-echo/175 ?
You have to discover devices both with pimatic and echo at the same time. You have 20 seconds for this.

**Comment by michbeck100** [comment]
Closing this issue. Please reopen if issue is not fixed with latest release.

**Comment by xCite1986** [comment]
ooh thanks, my bad.. the discover-devices button was the solution for my problem ;)

**Comment by n3roGit** [comment]
Hi still not working for me with the echo dot 2gen :(

**Comment by n3roGit** [comment]
Testet with Version 0.5. Started discover device in pimatic and in alexa multiple times

**Comment by n3roGit** [comment]
Changed nginx port to free port 80 but no luck

**Comment by michbeck100** [comment]
What does the log say? Is it still saying „pairing disabled“?

**Comment by michbeck100** [comment]
@n3roGit You say you are using nginx? This might be the issue. If you try to open the following url:
```
http://[PIMATIC]/api/foo/lights
```
Do you get a result? There should be a json containing all devices that are visible to Alexa. 
NOTE: You have to activate the discovery mode on pimatic, and access the url within the next 20 seconds. After that the "user" foo is saved.

**Comment by n3roGit** [comment]
This is my log:

debug [pimatic-echo]: Headers: {
  "host": "192.168.1.13",
  "accept": "*/*"
}
12:09:35debug [pimatic-echo]: GET Request to /api/t6QKkj8MZQa4BnGe4c2E1GCCOw4lGAjxy2EtN7iJ/groups/0
12:09:35debug [pimatic-echo]: Request: /api/t6QKkj8MZQa4BnGe4c2E1GCCOw4lGAjxy2EtN7iJ/groups/0
12:09:35debug [pimatic-echo]: Headers: {
  "host": "192.168.1.13",
  "accept": "*/*"
}
12:09:35debug [pimatic-echo]: GET Request to /api/t6QKkj8MZQa4BnGe4c2E1GCCOw4lGAjxy2EtN7iJ/groups/0
12:09:35debug [pimatic-echo]: Request: /api/t6QKkj8MZQa4BnGe4c2E1GCCOw4lGAjxy2EtN7iJ/groups/0
12:09:34debug [pimatic-echo]: Headers: {
  "host": "192.168.1.13",
  "accept": "*/*"
}
12:09:34debug [pimatic-echo]: GET Request to /api/t6QKkj8MZQa4BnGe4c2E1GCCOw4lGAjxy2EtN7iJ/groups/0
12:09:34debug [pimatic-echo]: Request: /api/t6QKkj8MZQa4BnGe4c2E1GCCOw4lGAjxy2EtN7iJ/groups/0
12:09:34debug [pimatic-echo]: Headers: {
  "host": "192.168.1.13",
  "accept": "*/*"
}
12:09:34debug [pimatic-echo]: GET Request to /api/t6QKkj8MZQa4BnGe4c2E1GCCOw4lGAjxy2EtN7iJ/groups/0
12:09:34debug [pimatic-echo]: Request: /api/t6QKkj8MZQa4BnGe4c2E1GCCOw4lGAjxy2EtN7iJ/groups/0
12:09:29debug [pimatic-echo]: Headers: {
  "host": "192.168.1.13",
  "accept": "*/*"
}

No i got this on your url:

Cannot GET /api/foo/lights

**Comment by n3roGit** [comment]
"NOTE: You have to activate the discovery mode on pimatic, and access the url within the next 20 seconds. After that the "user" foo is saved."

Yes i have done this, but no file is created

**Comment by n3roGit** [comment]
i redirect all after the first / to pimatic with nginx:


location / {
                proxy_pass http://127.0.0.1:8087;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header Host $host;
        }

**Comment by michbeck100** [comment]
Because you are using an echo dot, you don't have to use port 80 with pimatic-echo. Please use a different port which is not redirected by nginx. Just to be sure remove all devices from Alexa and do the complete device discovery from start to end. 
So you only need the port config, no other network related configs. Then you will see the requests from Alexa in your log. Use the UUID between api and groups to  create the URL:
```
http://[PIMATIC]/api/[UUID]/lights
``` 
BTW: You should also see requests from Alexa to this URL during discovery. If not, she didn't recognize your raspberry at all. 
If this all doesn't help, you can still setup a clean pimatic installation on your computer and start this just with pimatic-echo and some dummy devices. If Alexa finds them, you know at least that its not working because of your raspberry setup.

**Comment by michbeck100** [comment]
Im closing this since problems were solved.
