### ISSUE TITLE
Pimatic echo 0.4.8 milight ibox2

### ISSUE THREAD

**Issue by heiko1988** [michbeck100/pimatic-echo#39]
Hi,
i have upgrade pimatic -echo from 0.4.7 to 0.4.8
```

From Pimatic Start:
info [pimatic-echo]: started hue emulator on port 9876
12:54:32info [pimatic-echo]: Starting pimatic-echo...
....
.....
error [pimatic]: Invalid config of device "led-band-zone-4": Property "echo" is not a valid property
```

```
My Pimatic echo config
    {
      "plugin": "echo",
      "active": true,
      "comfyTemp": 23,
      "ecoTemp": 17,
      "debug": true,
      "trace": true,
      "address": "192.168.0.38",
      "port": 9876
    },
```

The plugin has always worked very well so far.
only after the update I get the error message.

I have the problem with the milight led lamps and controller for led. 
with the bridge ibox2 and in v6 work all normaly

i have the Amazon Echo Dot (2. Generation)

what I already tried:
1. without ip and mac adress and with ip and mac adress
2. delete plugin and reinstall
3. Pimatic Restart

If you need further information please let me know

Greeting Heiko

**Comment by michbeck100** [comment]
Please try the latest release. The error message is actually just a warning. To remove it, make sure to place pimatic-echo  at first in the plugin list in the config.json

**Comment by heiko1988** [comment]
Hi,

runs against wonderful :)

only a small problem still, if I hue port the haven not specified writes pimatic that it created by me variable can not describe.

if I do the same but give the port manually, then it works as it should.

thanks for the great plugin and your work on it :)

**Comment by michbeck100** [comment]
Sorry but i don't understand the problem. Maybe in german?

**Comment by heiko1988** [comment]
ja gerne in deutsch ist mir lieber :)

so nochmal, ich kann ja den hue port setzen, wenn ich den leer lasse. 
Dann startet pimatic durch bis es eine variable von mir beschreiben will.
Dann bricht auch der pimatic start ab in der konsole.

wenn ich aber in der config den hue port mit angebe, dann startet pimatic ohne Probleme.
Das ist eigentlich auch nichts so wichtiges, aber ich wollte es gesagt haben.

und mich nochmal für deine arbeit bedanken für das tolle plugin.

**Comment by michbeck100** [comment]
Wenn der Port weggelassen wird dann startet pimatic auf Port 80. hast du die Fehlermeldung?

**Comment by heiko1988** [comment]
Nein.
Ich meinte in der device config von dem echo plugin. Da kann man den Port von der hue emulation eintragen. Wenn ich da nichts eintrage. Und pimatic neu starte. Dann bricht der Start auch ab.

**Comment by michbeck100** [comment]
Was steht denn da im Log? Hast du auf Port 80 was anderes als pimatic laufen?

**Comment by heiko1988** [comment]
Auf dem Port 80 läuft der apache und pimatic auf Port 81


22:59:50.112 [pimatic] Could not update variable pv-statistik.Ca. € Pro Monat: Expected variable garten-pv-sonoff.Power to have a numeric value.
22:59:50.398 [pimatic-echo] udp server listening on port 1900
22:59:50.420 [pimatic] An uncaught exception occurred: Error: Error starting hue emulator. Port 80 is not available.
22:59:50.420 [pimatic]>    at Server.<anonymous> (/home/pi/pimatic-app/node_modules/pimatic-echo/echo.coffee:108:17)
22:59:50.420 [pimatic]>    at emitOne (events.js:77:13)
22:59:50.420 [pimatic]>    at Server.emit (events.js:169:7)
22:59:50.420 [pimatic]>    at emitErrorNT (net.js:1267:8)
22:59:50.420 [pimatic]>    at nextTickCallbackWith2Args (node.js:458:9)
22:59:50.420 [pimatic]>    at process._tickDomainCallback (node.js:413:17)
22:59:50.420 [pimatic]> This is most probably a bug in pimatic or in a module, please report it!
22:59:50.423 [pimatic] exiting...
root@raspberrypi:/home/pi/pimatic-app#

**Comment by michbeck100** [comment]
22:59:50.420 [pimatic] An uncaught exception occurred: Error: Error starting hue emulator. Port 80 is not available.

Da ist glaub ich eindeutig. Falls du einen Echo neuerer Generation hast musst du entweder den Port des Apache ändern oder nginx als Reverse-Proxy benutzen

**Comment by michbeck100** [comment]
Für die älteren Echos (zb. Echo dot) reicht es aber den Port in der Plugin config zu ändern

**Comment by michbeck100** [comment]
Ich glaube das Problem ist klar. Du hast was anderes auf port 80 laufen. Ich schliesse das Ticket
