### ISSUE TITLE
Feature request: get better response as "okay"

### ISSUE THREAD

**Issue by xCite1986** [michbeck100/pimatic-echo#4]
it would be also nice if alexa could be give back a better response what she really did. 
for now only "okay" responses...

example:
command: "alexa, turn Livingroom Light on" 
response: "okay, i've turned on the Light in the livingroom" or
"okay, i've turned Livingroom Light on"

or

command: "alexa, set the livingroom heating to 23 degrees" 
response: "okay, i've set the Livingroom temperature to 23 degrees"

**Comment by michbeck100** [comment]
Changing the response is currently not possible. See remains up to the Amazon echo team. See https://www.reddit.com/r/amazonecho/comments/3zi9qb/how_do_i_make_alexa_not_say_ok_after_completing/
