### ISSUE TITLE
Add HomematicHeatingThermostat

### ISSUE THREAD

**Issue by Venice-89** [michbeck100/pimatic-echo#40]
Hi,

would be nice to control Homematic HeatingThermostats from Pimatic Homegear Plugin :)

Thanks for your nice plugin, thanks for your work !

**Comment by michbeck100** [comment]
As far as I can tell this works already without any changes. Just make sure to set the thermostat device to active.

**Comment by michbeck100** [comment]
Closing this issue. Please reopen if it doesn't work with latest release

**Comment by Venice-89** [comment]
Hi,

today I tried to configure it. The device is listed in my alexa app as an dimmable light and alexa say "the device doesn't support that" if I try to change the temperature.

Greetings
Tobias

**Comment by michbeck100** [comment]
What did you say?

**Comment by michbeck100** [comment]
Please read the README.md carefully.
