### ISSUE TITLE
hue-port crashes pimatic 

### ISSUE THREAD

**Issue by cm86** [michbeck100/pimatic-echo#42]
The hue-port ist actually set to 80.
In you have a webserver installed,
Then pimatic crashes as startup...

I had to deaktivate the plugin or change the port manually...
But for the second way alexa doesn‘t notice any device

**Comment by michbeck100** [comment]
Currently there is no way to make the echo 2nd gen work without setting the port to 80. Thats why it's the default value. If you running a webserver on port 80 you have to choices:
1. Change the port of your webserver (obviously)
2. use a reverse-proxy (like nginx, please search the web for tutorials).
