### ISSUE TITLE
Request support for "Milight Reloaded" Devices

### ISSUE THREAD

**Issue by tehmilcho** [michbeck100/pimatic-echo#43]
Hi,

the Devices from the Plugin "milight reloaded" will not discovered in Alexa. All other Devices works fine.

Config of the Device:
{
      "ip": "192.168.1.81",
      "echo": {
        "additionalNames": [],
        "active": true
      },
      "id": "test",
      "name": "test",
      "class": "MilightFullColorZone",
      "zoneId": 1
    }

The Device has no Switch just one Silder for Color and one Silder for Dimming (0 - 100%) 
![milight](https://user-images.githubusercontent.com/22918349/33492159-8d6f7e1c-d6bc-11e7-9141-931e5fd39910.JPG)

The Problem is the other Milight Plugin (works fine) but dont support the new Devices from Milight.

If you need something more, let me know.

Greetings Milcho

**Comment by heiko1988** [comment]
Hi,

You can create a dummy switch, an make a rule. 

This work.

**Comment by michbeck100** [comment]
Or you just use 0.5.2 which was just released. This includes support for all milight lights that i found in plugin sources.
