### ISSUE TITLE
Hue-ZLL not working

### ISSUE THREAD

**Issue by ITTV-tools** [michbeck100/pimatic-echo#45]
Hi,
I cant configure huezlltemplight in pimatic-hue inside of the web gui.
If I configure it in the config is says: 
`Invalid config of device "deckenlampe-lukas": Property "echo" is not a valid property`
Alexa can find the device. But I can't control anything. She says "The device does not support this feature".

In the API are some variables missing.

state |  
-- | --
on | null
bri | 0
alert | "none"
reachable | true
type | "Dimmable light"
name | "Deckenlampe"
modelid | "LWB007"
manufacturername | "pimatic"
uniqueid | "00:17:88:5E:D3:01-01"
swversion | "66009461"

I guess thats not correct. 

Hope you can help.

**Comment by michbeck100** [comment]
What variables are missing?

**Comment by ITTV-tools** [comment]
sorry. Maybe its the wrong word for that. I mean state on = "null". Or is this correct ? Becauese alexa says turning off/on/dim the light is nur supportet by this device, if I try to control a huezllcolortemplight.

**Comment by michbeck100** [comment]
Oh, now I see. You are right. A star of null isn't correct. I'll have a look into this

**Comment by michbeck100** [comment]
Could you post the device config so I can see what type of light this is?

**Comment by ITTV-tools** [comment]
Sure    
{
      "class": "HueZLLColorTempLight",
      "name": "Deckenlampe",
      "hueId": 2,
      "ignoreReachability": true,
      "hap": {
        "service": "Lightbulb"
      },
      "id": "deckenlampe",
      "echo": {
        "name": "Deckenlampe",
        "additionalNames": [],
        "active": true
      }
    },

**Comment by michbeck100** [comment]
The problem is that pimatic-huezll doesn't set the state on starting, but when pimatic finished loading. At this moment pimatic-echo is already initialized and has the wrong state. I think I will set the state to false if this happens.

**Comment by ITTV-tools** [comment]
okay. Maybe pimatic huezll needs some time to contact the api of the bridge and parse the data. But  why does pimatic-echo not get the new state, after its done ?

**Comment by michbeck100** [comment]
Because, until now,  it was enough to get it when the device was added.

**Comment by michbeck100** [comment]
da2d326 should fix this for now. Could you test the latest commit?

**Comment by smarthomeagentur** [comment]
after a complete rescan it seems to work now. did not get any "not supported" messages since one day
