### ISSUE TITLE
 Echo can not find any devices

### ISSUE THREAD

**Issue by Skarhand** [michbeck100/pimatic-echo#46]
From the version 0.5.1 Alexa finds no devices in the search. The plugin is the first in the config. To search for new devices, the search is started in Pimatic, then the search for Alexa.

Here the link to the log .:
https://89.163.158.147/owncloud/index.php/s/Z93tpaaaUjXvEIt

**Comment by michbeck100** [comment]
what type of echo are you using? And how did you start the device discovery?

**Comment by Skarhand** [comment]
I have a Echo 1.Gen .
But you can close this Tiket. I have change my Pi (Gen1) to a new Pi (Gen3). Now I have reinstall Pimatic with the old config, and now Alexa find all my devices. 

Thank you for your Engagement. :-)

**Comment by b0711** [comment]
Echo 2nd Gen, does not find any devices with 0.5.2.

Debug log of serach: http://pasted.co/e5b8e9d5
password: pimatic

Hope this helps

**Comment by michbeck100** [comment]
Sorry but the new echo isn’t supported at the moment. Just the echo dot works

**Comment by b0711** [comment]
Yesterday it worked. I found the devices and i was able to use them. Then added more and it didnt find them. Then did this:

1. delete echo-database folder and node-modules/pimatic-echo from pimatic and restart pimatic
2. remove devices from alexa.amazon.com
3. start „discover devices“ in pimatic
4. let Alexa search for new devices.

and it doesnt find any.

**Comment by michbeck100** [comment]
Might be some silent firmware update on the echo. Mine worked in the first place, too. Now it doesn’t.

**Comment by b0711** [comment]
Just tested it with my Sonos One. It also couldnt find any devices.

**Comment by michbeck100** [comment]
I don’t think that the Sonos One will be able to switch anything without a skill. You would have to test with officially supported Hue lights to be sure

**Comment by b0711** [comment]
Are you planning to work on supporting the 2nd generation echo again?
Might developping an alexa skill be the "better" solution for this?

**Comment by michbeck100** [comment]
It might get supported again, if other hue emulators fix the bug. Then i will adapt this for pimatic-echo. And yes, a skill is definitely the best solution i guess, but this takes a little longer to develop.
