### ISSUE TITLE
Guest wifi fritzbox 

### ISSUE THREAD

**Issue by n3roGit** [michbeck100/pimatic-echo#49]
At the moment the guest wifi switch from the fritzbox plugin is shown as dimmable device in alexa

**Comment by michbeck100** [comment]
So are all other devices, too. That’s normal.

**Comment by n3roGit** [comment]
but it dosent work anymore :-/

**Comment by michbeck100** [comment]
That’s a different thing. Could you explain, what “doesn’t work” means?

**Comment by n3roGit** [comment]
Ich mach das mal eben auf deutsch :) über die app passiert nichts wenn ich das WLAN ein oder ausschalten will. Über Sprache sagt alexa nur "gastzugang unterstützt das nicht"
Nun habe ich dir drei Geräte (hab zwei alias dazu) entfernt und neu eingelesen. Bei einem der drei geht es jetzt über die app. Jedoch geht es bei keinem über einen sprach Befehl

**Comment by heiko1988** [comment]
Hi,

Ich klinke mich hier mal ein,
Habe das eben getestet mit dem Fritz gast wlan und geht ohne Probleme.
Alias Name habe ich keine eingerichtet, weil es bei mir da auch zu Problemen kam.

Habe dann das gast wlan dann in alexa selbst in eine Gruppe gemacht.
(Nur Das ich es nach meinem Wunsch namen aufrufen kann.)

Hardware:
Alexa echo dot 2 gen.
FB 6590 fw:6.85 (Die Neuste)

Über pimatic Selbst kannst aber schon das gast wlan an und ausschalten?
Was hast für Hardware im Einsatz?

Gruß Heiko

**Comment by n3roGit** [comment]
Moin,

ich hab ne 7490. Über Pimatic geht auch alles. Nur eben bei den Alias nicht immer,

Momentan funktioniert es immerhin bei dem primären namen.

Als Hardware habe ich mehrere Dots und einen der neuen Echos.

Für mich ist es so OK wie es gerade ist. Ich dachte nur, dass es vielleicht auch andere betrifft :)


Vielen Dank für den Support!

**Comment by michbeck100** [comment]
@n3roGit Nutzt du additionalNames oder name um den Namen zu überschreiben?

**Comment by n3roGit** [comment]
ja

**Comment by michbeck100** [comment]
@n3roGit geht es jetzt? Ich habe gemerkt, dass mit den Fritzbox Versionen > 7.0 das Einschalten des Wifi eh nicht mehr geht. Ich schließe das Ticket daher. Falls es noch etwas gibt bitte ins pimatic Forum oder neues Issue aufmachen
