### ISSUE TITLE
Feature request: ex- or include device

### ISSUE THREAD

**Issue by xCite1986** [michbeck100/pimatic-echo#5]
it would be nice to ex- or include devices that some devices are not recognized by alexa.

```
"devices": [
  {
    "id": "switch",
    "class": "DummySwitch",
    "name": "Switch",
    "echo": {
       "include": true
    }
  }
]
```

**Comment by michbeck100** [comment]
Implemented with version 0.0.3

**Comment by michbeck100** [comment]
By default all supported devices are included and you have to set an exclude flag. See README.md for help.

**Comment by xCite1986** [comment]
thx, great job 👍
