### ISSUE TITLE
z-way z-wave devices no longer work with the echo

### ISSUE THREAD

**Issue by thexperiments** [michbeck100/pimatic-echo#50]
After the last updates I completely deleted all devices from echo/alexa and added them again. I now cant dim or switch my z-way devices anymore.

"Alexa, dim fancy light to 10%" --> "Sorry, fancy light does not support this"
"Alexa turn on fancy light" --> "Sorry fancy light doesn't answer"

Dummy switches seem to work fine.
Can't see any error messages in the log.

**Comment by michbeck100** [comment]
Please try device names without spaces. I found that these names confuse Alexa.

**Comment by michbeck100** [comment]
@thexperiments did you solve the problems?

**Comment by thexperiments** [comment]
I think it was magically resolved, I at least controlled an z-way device last week via alexa, even with a space in the name
