### ISSUE TITLE
No devices found with my alexa after discovering for new devices

### ISSUE THREAD

**Issue by blacktiger333** [michbeck100/pimatic-echo#52]
I wanted to discover for new devices with my alexa - but no devices were found. I started to discover devices within pimatic and soon afterward with alexa. I also already removed all existing devices within alexa and reinstalled the echo plugin in pimatic. I'm using more than one echo dots 2nd generation (3) and use more raspis - with the other ones everything works fine - but not with this one I use.

Can you see something what's wrong with the log file and config I sent?

[pimatic-daemon.log](https://github.com/michbeck100/pimatic-echo/files/1604062/pimatic-daemon.log)

[config.txt](https://github.com/michbeck100/pimatic-echo/files/1604034/config.txt)

**Comment by michbeck100** [comment]
Are you using the echo plugin in more than one of the Raspi’s

**Comment by blacktiger333** [comment]
Yes - is this a problem?

Am 04.01.2018 um 19:51 schrieb Michael Kotten <notifications@github.com<mailto:notifications@github.com>>:


Are you using the echo plugin in more than one of the Raspi’s

**Comment by michbeck100** [comment]
I’m not sure. Please start by disabling the other instances.

**Comment by blacktiger333** [comment]
I disabled all other instances - but it doesn't help, same problem as before. FYI: I also run HA Bridge on this raspi (on port 90) - also tried it after I stopped HA Bridge service, so assume this should not be the reason. It's quite strange - I don't have an idea why just this raspi doesn't work with your plugin. I need the echo plugin on this raspi because of devices I want to switch with echo....

**Comment by michbeck100** [comment]
Are you using the echo dot, or the newer echo?

**Comment by blacktiger333** [comment]
I'm using the echo dot.

**Comment by The-Saint2k** [comment]
@blacktiger333 
put the echo plugin in the config file at the beginning of the section. Like this:

  "plugins": [
    {
      "plugin": "echo",
      "active": true,
      "debug": true
    },
...............


I had the same problem and found this solution in the forum or here on github.

@michbeck100 
thank you for your nice plugin

**Comment by blacktiger333** [comment]
I tried both - disabled all other instances (shut down other raspis) - and did the echo plugin at the beginning of the section, it doesn't help. This is really a strange behavior - I'm the only one with this problem? What I didn't so far is a complete reinstall of my raspi and pimatic - but this is something what I don't want to do now (because all other services are working so far). I join in congratulation of The-Saint2k: @michbeck100 : this is a nice plugin.

**Comment by michbeck100** [comment]
You wrote 

> I'm using more than one echo dots 2nd generation (3) and use more raspis - with the other ones everything works fine - but not with this one I use.

Does this mean, that you have the echo plugin working on the other raspis and your echo also discovered the devices from these pimatic instances?

**Comment by blacktiger333** [comment]
Currently I only use the 2nd raspi with devices for echo. Yes – the second raspi discover all 4 devices I have there – but 2 of them are showing as offline (and cannot be switched with echo) .

Von: Michael Kotten<mailto:notifications@github.com>
Gesendet: Donnerstag, 8. Februar 2018 10:57
An: michbeck100/pimatic-echo<mailto:pimatic-echo@noreply.github.com>
Cc: blacktiger333<mailto:chris3chris3chris@hotmail.com>; Mention<mailto:mention@noreply.github.com>
Betreff: Re: [michbeck100/pimatic-echo] No devices found with my alexa after discovering for new devices (#52)


You wrote

I'm using more than one echo dots 2nd generation (3) and use more raspis - with the other ones everything works fine - but not with this one I use.

Does this mean, that you have the echo plugin working on the other raspis and your echo also discovered the devices from these pimatic instances?

**Comment by michbeck100** [comment]
Really, i have no idea if this can work. I haven't tested with multiple pimatic-echo instances. Even if you switch off all other raspis, you still have the devices stored in the Alexa "memory" in the Amazon cloud. Maybe you have to remove all these devices first, and then try again. And even if it works then, you have the same problem again with your other raspi that was working before. I guess that each pimatic-echo instance needs some unique identifier. But currently i have no idea what this could be. I you like you can play around with some values in hue.coffee starting from here: https://github.com/michbeck100/pimatic-echo/blob/master/lib/hue.coffee#L290

**Comment by michbeck100** [comment]
Is this still an issue?

**Comment by michbeck100** [comment]
I'm closing this issue for now. Feel free to reopen if the issue still exists
