### ISSUE TITLE
v0.5.3: pimatic api requests raise "User not found" error

### ISSUE THREAD

**Issue by mwittig** [michbeck100/pimatic-echo#54]
See https://forum.pimatic.org/topic/4101/problem-with-api-devices

Possibly caused by commit https://github.com/michbeck100/pimatic-echo/commit/c4100ca190e1f27fca4388f787b1335960e7caa5

**Comment by michbeck100** [comment]
If pimatic-echo says the path /api/devices is not allowed, why doesn’t pimatic override this? Is this intended behavior?

**Comment by michbeck100** [comment]
should be fixed by now
