### ISSUE TITLE
Support of pimatic plugin "samsung-tv-2016"?

### ISSUE THREAD

**Issue by station7** [michbeck100/pimatic-echo#55]
Hi, 

the easy to configure plugin "samsung-tv-2016" (https://github.com/aap82/pimatic-samsung-tv-2016) allows to power Samsung TVs 2016+ on and off. With your pimatic-hap plugin I can successfully turn my Samsung TV on and off with Siri's help, but the pimatic-echo plugin unfortunately does not work in this respect. Alexa finds the device, but when I ask Alexa to power on the TV or use the Alexa App it says "Server reagiert nicht" or "Diese Funktion wird nicht unterstützt". Let me know if you are interested in investigating the error and if I can be of any help tracing it down.

**Comment by michbeck100** [comment]
Do you see something in the logs when switching using pimatic-echo? Lets see you device config from config.json.

**Comment by station7** [comment]
Thanks for looking into this. Here is device config: 

    {
      "ip_address": "192.168.10.155",
      "mac_address": "",
      "echo": {
        "additionalNames": [],
        "active": true
      },
      "hap": {
        "service": "Lightbulb"
      },
      "id": "samsung",
      "name": "Samsung",
      "class": "SamsungTV_2016"
    }

The logs follow later today.

**Comment by station7** [comment]
Sorry, nothing particular in the logs. I cannot even switch on the TV with the Alexa App, as it always says "Gerät reagiert nicht". 

This is all I repeatedly see in the logs (with pimatic-echo debug enabled):

```
debug [pimatic-echo]: Headers: {
  "host": "192.168.10.20",
  "accept": "*/*"
}
15:45:56debug [pimatic-echo]: GET Request to /api/1ZgOiXs68gvzrGfJJcqPRQJM80hMDFzOosUMqz3d/lights/22
15:45:56debug [pimatic-echo]: Request: /api/1ZgOiXs68gvzrGfJJcqPRQJM80hMDFzOosUMqz3d/lights/22
15:45:53debug [pimatic-echo]: Headers: {
  "host": "192.168.10.20",
  "accept": "*/*"
}
15:45:53debug [pimatic-echo]: GET Request to /api/1ZgOiXs68gvzrGfJJcqPRQJM80hMDFzOosUMqz3d/lights/22
15:45:53debug [pimatic-echo]: Request: /api/1ZgOiXs68gvzrGfJJcqPRQJM80hMDFzOosUMqz3d/lights/22
15:45:53debug [pimatic-echo]: complete sending all responses.
15:45:53debug [pimatic-echo]: >> sent response ssdp discovery response: HTTP/1.1 200 OK
HOST: 239.255.255.250:1900
EXT:
CACHE-CONTROL: max-age=100
LOCATION: http://192.168.10.20:80/description.xml
SERVER: FreeRTOS/7.4.2, UPnP/1.0, IpBridge/1.19.0
hue-bridgeid: B827EBFFFECD5326
ST: uuid: 2f402f80-da50-11e1-9b23-b827ebcd5326
USN: uuid:2f402f80-da50-11e1-9b23-b827ebcd5326::upnp:rootdevice

15:45:53debug [pimatic-echo]: >> sent response ssdp discovery response: HTTP/1.1 200 OK
HOST: 239.255.255.250:1900
EXT:
CACHE-CONTROL: max-age=100
LOCATION: http://192.168.10.20:80/description.xml
SERVER: FreeRTOS/7.4.2, UPnP/1.0, IpBridge/1.19.0
hue-bridgeid: B827EBFFFECD5326
ST: urn:schemas-upnp-org:device:basic:1
USN: uuid:2f402f80-da50-11e1-9b23-b827ebcd5326::upnp:rootdevice

15:45:53debug [pimatic-echo]: >> sent response ssdp discovery response: HTTP/1.1 200 OK
HOST: 239.255.255.250:1900
EXT:
CACHE-CONTROL: max-age=100
LOCATION: http://192.168.10.20:80/description.xml
SERVER: FreeRTOS/7.4.2, UPnP/1.0, IpBridge/1.19.0
hue-bridgeid: B827EBFFFECD5326
ST: upnp:rootdevice
USN: uuid:2f402f80-da50-11e1-9b23-b827ebcd5326::upnp:rootdevice

15:45:53debug [pimatic-echo]: << server got: M-SEARCH * HTTP/1.1
Host: 239.255.255.250:1900
Man: "ssdp:discover"
ST: ssdp:all
MX: 5

```

**Comment by michbeck100** [comment]
@station7 did you solve your issue?

**Comment by station7** [comment]
Hi michbeck, 

many thanks for following up. Actually, I have not been able to solve the issue but used a workaround and created rules for switching on the TV via standard Wake-on-lan command and switching it off with a shell/python command using samsungctl. While writing, I re-enable pimatic-echo for samsung-tv-2016 but still not luck: Alexa app shows the device but complains "Server reagiert nicht" and I am unable to switch it on or off. Sorry...

**Comment by michbeck100** [comment]
Do you see anything in the logs when trying to switch?

**Comment by station7** [comment]
Unfortunately not, but honestly, I do not know what to look for. pimatic-echo has no entries in its error logs and the debug logs of pimatic-echo do not seem worrying... Where and what should I look for?

**Comment by michbeck100** [comment]
I did have a look into the samsung-tv-2016 plugin and I found that I doesn't return a promise for `changeStateTo`. This could be the problem. If this issue is still alive, then you might have to ask the maintainer of the plugin for a change.

**Comment by michbeck100** [comment]
As the Plugin wasn‘t updated, I close this issue.
