### ISSUE TITLE
Alexa on Sonos One

### ISSUE THREAD

**Issue by Ptrvh** [michbeck100/pimatic-echo#56]
Hello,

I use a Sonos One with Alexa. I't does work with my Hue lights. It does not find any devices from Pimatic. Isn't it necessary to link pimatic to Alexa as I did with Hue or Tradfri with the Skills?

**Comment by michbeck100** [comment]
You need an pimatic skill to link your Sonos. But this doesn’t exist yet. Keep your fingers crossed that I find the time soon to implement this. The first steps are done but I’m still working on this.

**Comment by Ptrvh** [comment]
Fingers Crossed 👍 . If I can test something then let me know!

**Comment by michbeck100** [comment]
I'm closing this, as the skill won't be developed as part of pimatic-echo here.
