### ISSUE TITLE
Echo Dot 1st gen stopped working 

### ISSUE THREAD

**Issue by martially1965** [michbeck100/pimatic-echo#59]
Hi,
first of all, my thanks for the good times your plugin gave my family. Unfortunately, these are somehow interrupted currently. 
A couple of month ago (sorry, I was to lazy and to busy for caring about it earlier) Alexa stopped working on may pimatic-echo devices. Now, looking at the things brings up no error messages but alexa was showing the devices "offline". I deleted them and now they are not found anymore. 
It´s an Echo Dot 1st gen.

root@msi-raspi:/opt/pimatic-app/node_modules/pimatic# DEBUG=ssdp-server node pimatic.js
module.js:327
    throw err;
    ^

Error: Cannot find module 'fs.extra'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/opt/pimatic-app/node_modules/pimatic/coffee-cache.js:27:14)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
root@msi-raspi:/opt/pimatic-app/node_modules/pimatic#

Thought, it moans about fs.extra, Pimatic starts.  

Do you have a hint for me?

Best, Martin

**Comment by michbeck100** [comment]
You could try to install the module manually. Just run this in /opt/pimatic-app/node_modules/pimatic:
```
$ sudo npm install 
```
This should install fs.extra. If this doesn't work, try to reinstall the latest version using your existing config.json.

**Comment by michbeck100** [comment]
@martially1965 Did you solve your issue?

**Comment by martially1965** [comment]
Thanks,

 

it is solved. I think it was by removing and re-installing the plugin
 

--
Mit freundlichen Grüßen / Best Regards / Meilleures Salutations

Martin Siwek


Quote of the life: "Ich distanziere mich von allem, was ich denke"

 
 

Gesendet: Dienstag, 26. Februar 2019 um 21:51 Uhr
Von: "Michael Kotten" <notifications@github.com>
An: michbeck100/pimatic-echo <pimatic-echo@noreply.github.com>
Cc: martially1965 <martinsi@web.de>, Mention <mention@noreply.github.com>
Betreff: Re: [michbeck100/pimatic-echo] Echo Dot 1st gen stopped working (#59)


@martially1965 Did you solve your issue?
