### ISSUE TITLE
Feature request: ask for devices and get data back (Q/A)

### ISSUE THREAD

**Issue by xCite1986** [michbeck100/pimatic-echo#6]
include a question/answer response to get som data back was also great,

like

HomeduinoRFTemperature device
question "alexa, how warm is it in the workroom?"
answer: "the temperature of workroom was 22 comma 8 degrees"

switch devices:
question "alexa, was the state of livingroom on?"
answer: "yes, livingroom was on"

thermostat devices:
question "alexa, how was the state in livingroom heating?"
answer: "the livingroom heating was set to 22 degrees and in eco mode"

presence devices?

**Comment by michbeck100** [comment]
Currently asking Alexa for the current state of a devic is not supported without a special skill. A pimatic skill would require a lot more work, and will not be possible with a simple plugin. It requires pimatic to be accessible from the internet, requires an oauth2 login mechanism and also some software which needs to run in Amazons AWS Cloud, which even costs money. Maybe some day i have the time do write all this, but this will not be part of this plugin.
