### ISSUE TITLE
Unable to connect echo dot to pimatic

### ISSUE THREAD

**Issue by Mostum** [michbeck100/pimatic-echo#60]
I have tried it for some time now and dont see any success so far.
What am i doing wrong?

```
<< server got: M-SEARCH * HTTP/1.1
 >HOST: 239.255.255.250:1900
 >MAN: "ssdp:discover"
 >MX: 15
 >ST: urn:schemas-upnp-org:device:basic:1
 >
 > from 192.168.178.67:50000
  >> sent response ssdp discovery response: HTTP/1.1 200 OK
 >HOST: 239.255.255.250:1900
 >EXT:
 >CACHE-CONTROL: max-age=100
 >LOCATION: http://192.168.178.24:80/description.xml
 >SERVER: FreeRTOS/7.4.2, UPnP/1.0, IpBridge/1.19.0
 >hue-bridgeid: B827EBFFFEC09B5C
 >ST: upnp:rootdevice
 >USN: uuid:2f402f80-da50-11e1-9b23-b827ebc09b5c::upnp:rootdevice
 >
 >
  >> sent response ssdp discovery response: HTTP/1.1 200 OK
 >HOST: 239.255.255.250:1900
 >EXT:
 >CACHE-CONTROL: max-age=100
 >LOCATION: http://192.168.178.24:80/description.xml
 >SERVER: FreeRTOS/7.4.2, UPnP/1.0, IpBridge/1.19.0
 >hue-bridgeid: B827EBFFFEC09B5C
 >ST: urn:schemas-upnp-org:device:basic:1
 >USN: uuid:2f402f80-da50-11e1-9b23-b827ebc09b5c::upnp:rootdevice
 >
 >
  >> sent response ssdp discovery response: HTTP/1.1 200 OK
 >HOST: 239.255.255.250:1900
 >EXT:
 >CACHE-CONTROL: max-age=100
 >LOCATION: http://192.168.178.24:80/description.xml
 >SERVER: FreeRTOS/7.4.2, UPnP/1.0, IpBridge/1.19.0
 >hue-bridgeid: B827EBFFFEC09B5C
 >ST: uuid: 2f402f80-da50-11e1-9b23-b827ebc09b5c
 >USN: uuid:2f402f80-da50-11e1-9b23-b827ebc09b5c::upnp:rootdevice
 >
 >
  complete sending all responses.
  << server got: M-SEARCH * HTTP/1.1
 >HOST: 239.255.255.250:1900
 >MAN: "ssdp:discover"
 >MX: 15
 >ST: urn:schemas-upnp-org:device:basic:1
 >
 > from 192.168.178.67:50000
  >> sent response ssdp discovery response: HTTP/1.1 200 OK
 >HOST: 239.255.255.250:1900
 >EXT:
 >CACHE-CONTROL: max-age=100
 >LOCATION: http://192.168.178.24:80/description.xml
 >SERVER: FreeRTOS/7.4.2, UPnP/1.0, IpBridge/1.19.0
 >hue-bridgeid: B827EBFFFEC09B5C
 >ST: upnp:rootdevice
 >USN: uuid:2f402f80-da50-11e1-9b23-b827ebc09b5c::upnp:rootdevice
 >
 >
  >> sent response ssdp discovery response: HTTP/1.1 200 OK
 >HOST: 239.255.255.250:1900
 >EXT:
 >CACHE-CONTROL: max-age=100
 >LOCATION: http://192.168.178.24:80/description.xml
 >SERVER: FreeRTOS/7.4.2, UPnP/1.0, IpBridge/1.19.0
 >hue-bridgeid: B827EBFFFEC09B5C
 >ST: urn:schemas-upnp-org:device:basic:1
 >USN: uuid:2f402f80-da50-11e1-9b23-b827ebc09b5c::upnp:rootdevice
 >
 >
  >> sent response ssdp discovery response: HTTP/1.1 200 OK
 >HOST: 239.255.255.250:1900
 >EXT:
 >CACHE-CONTROL: max-age=100
 >LOCATION: http://192.168.178.24:80/description.xml
 >SERVER: FreeRTOS/7.4.2, UPnP/1.0, IpBridge/1.19.0
 >hue-bridgeid: B827EBFFFEC09B5C
 >ST: uuid: 2f402f80-da50-11e1-9b23-b827ebc09b5c
 >USN: uuid:2f402f80-da50-11e1-9b23-b827ebc09b5c::upnp:rootdevice
 >
 >
  complete sending all responses.
  Request: /description.xml
  GET Request to /description.xml
  Headers: {
 >  "host": "192.168.178.24",
 >  "accept": "*/*"
 >}
  Request: /description.xml
  GET Request to /description.xml
  Headers: {
 >  "host": "192.168.178.24",
 >  "accept": "*/*"
 >}
  Request: /api/3arqLKYLjcWiPo78tGnMWZ888bEW70167XQSgI7g/lights
  GET Request to /api/3arqLKYLjcWiPo78tGnMWZ888bEW70167XQSgI7g/lights
  Headers: {
 >  "host": "192.168.178.24",
 >  "accept": "*/*"
 >}
  Request: /api/3arqLKYLjcWiPo78tGnMWZ888bEW70167XQSgI7g/lights
  GET Request to /api/3arqLKYLjcWiPo78tGnMWZ888bEW70167XQSgI7g/lights
  Headers: {
 >  "host": "192.168.178.24",
 >  "accept": "*/*"
 >}
  << server got: M-SEARCH * HTTP/1.1
 >HOST: 239.255.255.250:1900
 >MAN: "ssdp:discover"
 >MX: 2
 >ST: ssdp:all
 >
 > from 192.168.178.57:52730
  >> sent response ssdp discovery response: HTTP/1.1 200 OK
 >HOST: 239.255.255.250:1900
 >EXT:
 >CACHE-CONTROL: max-age=100
 >LOCATION: http://192.168.178.24:80/description.xml
 >SERVER: FreeRTOS/7.4.2, UPnP/1.0, IpBridge/1.19.0
 >hue-bridgeid: B827EBFFFEC09B5C
 >ST: upnp:rootdevice
 >USN: uuid:2f402f80-da50-11e1-9b23-b827ebc09b5c::upnp:rootdevice
 >
 >
  >> sent response ssdp discovery response: HTTP/1.1 200 OK
 >HOST: 239.255.255.250:1900
 >EXT:
 >CACHE-CONTROL: max-age=100
 >LOCATION: http://192.168.178.24:80/description.xml
 >SERVER: FreeRTOS/7.4.2, UPnP/1.0, IpBridge/1.19.0
 >hue-bridgeid: B827EBFFFEC09B5C
 >ST: urn:schemas-upnp-org:device:basic:1
 >USN: uuid:2f402f80-da50-11e1-9b23-b827ebc09b5c::upnp:rootdevice
 >
 >
  >> sent response ssdp discovery response: HTTP/1.1 200 OK
 >HOST: 239.255.255.250:1900
 >EXT:
 >CACHE-CONTROL: max-age=100
 >LOCATION: http://192.168.178.24:80/description.xml
 >SERVER: FreeRTOS/7.4.2, UPnP/1.0, IpBridge/1.19.0
 >hue-bridgeid: B827EBFFFEC09B5C
 >ST: uuid: 2f402f80-da50-11e1-9b23-b827ebc09b5c
 >USN: uuid:2f402f80-da50-11e1-9b23-b827ebc09b5c::upnp:rootdevice
 >
 >
  complete sending all responses.
 [pimatic] pimatic-echo: Pairing mode is disabled again.

```

192.168.178.24 is the pi
and
192.168.178.67 is the echo dot

**Comment by michbeck100** [comment]
Looks fine to me. You could try to reset the port of pimatic-echo to the default instead of port 80. And of course make sure to use the most recent version. 
Another hint would be if you could tell what the request to /api/3arqLKYLjcWiPo78tGnMWZ888bEW70167XQSgI7g/lights brings up. Maybe it shows no devices.

**Comment by Mostum** [comment]
Isnt port 80 the default port?

**Comment by MaxWinterstein** [comment]
@Mostum still having problems with this? 

As seen in the logs file provided, there is a request from you alexa to `[...]/api/[...]lights` which means your alexa is reading the devices.

You can simply put this in your browser by adding your pimatic installation first.

e.g.:
```
  Request: /api/3arqLKYLjcWiPo78tGnMWZ888bEW70167XQSgI7g/lights
  GET Request to /api/3arqLKYLjcWiPo78tGnMWZ888bEW70167XQSgI7g/lights
  Headers: {
 >  "host": "192.168.178.24",
```
The host is your pimatic installation, the request the URL.
Please open http://192.168.178.24/api/3arqLKYLjcWiPo78tGnMWZ888bEW70167XQSgI7g/lights and show us the output.

**Comment by Mostum** [comment]
Yes, still the same, here is the output from the browser

> {}

And here are the logs from pimatic itself

>15:03:18.656 [pimatic-echo] Request: /api/3arqLKYLjcWiPo78tGnMWZ888bEW70167XQSgI7g/lights
15:03:18.662 [pimatic-echo] GET Request to /api/3arqLKYLjcWiPo78tGnMWZ888bEW70167XQSgI7g/lights
15:03:18.666 [pimatic-echo] Headers: {
15:03:18.666 [pimatic-echo]>  "host": "192.168.178.24",
15:03:18.666 [pimatic-echo]>  "connection": "keep-alive",
15:03:18.666 [pimatic-echo]>  "cache-control": "max-age=0",
15:03:18.666 [pimatic-echo]>  "upgrade-insecure-requests": "1",
15:03:18.666 [pimatic-echo]>  "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36",
15:03:18.666 [pimatic-echo]>  "dnt": "1",
15:03:18.666 [pimatic-echo]>  "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8",
15:03:18.666 [pimatic-echo]>  "accept-encoding": "gzip, deflate",
15:03:18.666 [pimatic-echo]>  "accept-language": "de-DE,de;q=0.9,en-GB;q=0.8,en;q=0.7,en-US;q=0.6",
15:03:18.666 [pimatic-echo]>  "cookie": "pimatic.sess=eyJ0aGVtZSI6ImdyYXBoaXRlL3JveWFsIiwidXNlcm5hbWUiOiJhZG1pbiIsImxvZ2luVG9rZW4iOiJmYWE4ZDhmZTQ2MzBmNWI1YWIxZTk0MjkxNmMyZDk5MDNhZThhZTNlN2MxODdmNDQ5ZmUxOWMzY2ExOWU4YWE4Iiwicm9sZSI6ImFkbWluIiwicmVtZW1iZXJNZSI6dHJ1ZX0=; pimatic.sess.sig=HuhM4ZfRVG84vAewo5gFv-A2o5s; io=zuPMx_LX2fRgaeTUAAAE",
15:03:18.666 [pimatic-echo]>  "if-none-match": "W/\"2-vyGp6PvFo4RvsFtPoIWeCReyIC8\""
15:03:18.666 [pimatic-echo]>}
15:03:18.743 [pimatic-echo] Request: /favicon.ico
15:03:18.746 [pimatic-echo] GET Request to /favicon.ico
15:03:18.749 [pimatic-echo] Headers: {
15:03:18.749 [pimatic-echo]>  "host": "192.168.178.24",
15:03:18.749 [pimatic-echo]>  "connection": "keep-alive",
15:03:18.749 [pimatic-echo]>  "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36",
15:03:18.749 [pimatic-echo]>  "dnt": "1",
15:03:18.749 [pimatic-echo]>  "accept": "image/webp,image/apng,image/*,*/*;q=0.8",
15:03:18.749 [pimatic-echo]>  "referer": "http://192.168.178.24/api/3arqLKYLjcWiPo78tGnMWZ888bEW70167XQSgI7g/lights",
15:03:18.749 [pimatic-echo]>  "accept-encoding": "gzip, deflate",
15:03:18.749 [pimatic-echo]>  "accept-language": "de-DE,de;q=0.9,en-GB;q=0.8,en;q=0.7,en-US;q=0.6",
15:03:18.749 [pimatic-echo]>  "cookie": "pimatic.sess=eyJ0aGVtZSI6ImdyYXBoaXRlL3JveWFsIiwidXNlcm5hbWUiOiJhZG1pbiIsImxvZ2luVG9rZW4iOiJmYWE4ZDhmZTQ2MzBmNWI1YWIxZTk0MjkxNmMyZDk5MDNhZThhZTNlN2MxODdmNDQ5ZmUxOWMzY2ExOWU4YWE4Iiwicm9sZSI6ImFkbWluIiwicmVtZW1iZXJNZSI6dHJ1ZX0=; pimatic.sess.sig=HuhM4ZfRVG84vAewo5gFv-A2o5s; io=zuPMx_LX2fRgaeTUAAAE",
15:03:18.749 [pimatic-echo]>  "if-none-match": "W/\"0-2jmj7l5rSw0yVb/vlWAYkK/YBwk\""
15:03:18.749 [pimatic-echo]>}

**Comment by MaxWinterstein** [comment]
> Yes, still the same, here is the output from the browser
> `{}`

`{}` is a nice little empty object. 
You may check the following:
* make sure the pimatic-echo plugin is first in the `config.json`
* make sure to have at least one device set to active within the echo configuraiton part, either via `config.json` like
```json
    {
      "id": "wohnzimmer-heizung",
      "class": "MaxHeatingThermostat",
      "name": "Heizung",
      "rfAddress": "09e1a3",
      "guiShowPresetControl": false,
      "echo": {
        "name": "Wohnzimmer Heizung",
        "additionalNames": [],
        "active": true
      }
    },
```
or via gui
![image](https://user-images.githubusercontent.com/5927148/47617752-c64d3e00-daca-11e8-89cd-15606b89ed49.png)

you may upload your pimatic `config.json` (remember to remove the user passwords if shown).

*but* i would guess, you have no device enabled.

**Comment by Mostum** [comment]
`make sure the pimatic-echo plugin is first in the config.json`

That did the job for me, thanks a lot!

**Comment by michbeck100** [comment]
Closing issue as it is resolved
