### ISSUE TITLE
Feature Request: Support openhr20 Thermostat

### ISSUE THREAD

**Issue by hannemann** [michbeck100/pimatic-echo#61]
Hello,

i tried out [openhr20](https://github.com/hannemann/pimatic-plugin-openhr20) by adding openhr20-thermostat to the heating templates and it works.

Could you please add it to your code?

**Comment by michbeck100** [comment]
Just create a pull request with your changes. Then i can review and merge your changes

**Comment by michbeck100** [comment]
@hannemann Any updates here?

**Comment by hannemann** [comment]
Hi Michael,

I was pretty sure i wrote an answer but obviously i didn't... Sorry.

Works like expected.  

Thank you, Hannemann

Am 26. Februar 2019 21:42:37 MEZ schrieb Michael Kotten <notifications@github.com>:
