### ISSUE TITLE
Support new generations 2 and 3

### ISSUE THREAD

**Issue by mat1990dj** [michbeck100/pimatic-echo#64]
It would be great to support gen 2 and gen 3 devices without having a gen 1 to search the devices.
What is the limitation?

**Comment by michbeck100** [comment]
AFAIK there is no native support built into the newer echo devices. This may have changed. If you have news about this from other smart home platforms, please let me know.

**Comment by mat1990dj** [comment]
You mean that the new echo devices are not compatible with HUE hubs?

**Comment by michbeck100** [comment]
No, they are. What i mean is, they changed something, so that the communication between the hue bridge and the newer echoes differs. But you can always proof me wrong. If you have a new echo just try.

**Comment by michbeck100** [comment]
Yes, but maybe other solutions like [ha-bridge](https://github.com/bwssytems/ha-bridge) are working. I have never tried. Maybe you have the time to test? if it's working then they implemented  something more than me.

**Comment by michbeck100** [comment]
https://github.com/bwssytems/ha-bridge/issues/890 has some findings whats working with ha-bridge

**Comment by michbeck100** [comment]
Closing this ticket as the newer generations are only supported by the upcoming pimatic skill
