### ISSUE TITLE
Pimatic failed to start after Reboot from Raspberry 

### ISSUE THREAD

**Issue by tehmilcho** [michbeck100/pimatic-echo#65]
Hey,

i must today Reboot my Raspberry and now pimatic failed every time to start. 

14:54:04.533 [pimatic-echo] debug: udp server listening on port 1900
14:54:04.589 [pimatic] error: An uncaught exception occurred: Error: addMembership ENODEV
14:54:04.589 [pimatic] error:>    at exports._errnoException (util.js:870:11)
14:54:04.589 [pimatic] error:>    at Socket.addMembership (dgram.js:438:11)
14:54:04.589 [pimatic] error:>    at Socket.<anonymous> (/home/pi/pimatic-app/node_modules/pimatic-echo/lib/upnp.coffee:36:19)
14:54:04.589 [pimatic] error:>    at emitNone (events.js:67:13)
14:54:04.589 [pimatic] error:>    at Socket.emit (events.js:166:7)
14:54:04.589 [pimatic] error:>    at startListening (dgram.js:121:10)
14:54:04.589 [pimatic] error:>    at dgram.js:221:7
14:54:04.589 [pimatic] error:>    at nextTickCallbackWith3Args (node.js:453:9)
14:54:04.589 [pimatic] error:>    at process._tickCallback (node.js:359:17)
14:54:04.589 [pimatic] error:> This is most probably a bug in pimatic or in a module, please report it!

**Comment by michbeck100** [comment]
Seems that there are no network connections available when starting pimatic. ENODEV means `Error: no device`(http://www-numi.fnal.gov/offline_software/srt_public_context/WebDocs/Errors/unix_system_errors.html).

**Comment by tehmilcho** [comment]
Mhh okay but that makes no sense =( Im connected via RDP and via SSH to the Raspberry.

**Comment by michbeck100** [comment]
Maybe it's trying to use a different interface? Not sure why this happens

**Comment by tehmilcho** [comment]
The Strange thing is it works all fine, than my Internet crashed.. and Pimatic makes some Strange Errors so i reboot the Raspberry .. now is pimatic dead ... i dont get it

**Comment by treban** [comment]
@tehmilcho Check if there is another process listening on the same port (udp/1900)
```
sudo netstat -anop --inet | grep 1900 
```

**Comment by tehmilcho** [comment]
I got no Output from "sudo netstat -anop --inet | grep 1900". if i do "sudo netstat -anop" i get this: 
unix  3      [ ]         STREAM     VERBUNDEN     1900     1/init

**Comment by michbeck100** [comment]
Sounds network related. But i can’t tell what’s the problem from here.

**Comment by tehmilcho** [comment]
year i think you are right.  Connected to the Raspberry Desktop and tried to open google over the Browser without success. But i dont understand why.

**Comment by tehmilcho** [comment]
i found it. It wars a DNS fail config... dont i ask new why this happend by a simple reboot of the Raspberry (i dont changed anything about it). 

Solution: 
/etc/resolv.conf
-> Change "nameserver" to the Ip of your Router
