### ISSUE TITLE
cant see any device in alexa

### ISSUE THREAD

**Issue by n3roGit** [michbeck100/pimatic-echo#7]
I have scanned my network several times but cant see any devices. i have set the logging to debug but i have no log entrys from the plugin.

regards

**Comment by philicibine** [comment]
I have the same issue.  Although I don't have an echo, so I am using alexapi.

**Comment by michbeck100** [comment]
@n3roGit are you using a real echo?

**Comment by n3roGit** [comment]
Yes I have two echo dots :)

**Comment by michbeck100** [comment]
Ok, i was using the alexa app to start the discovery and it took me 2 attempts, but then it worked. 
You could try to start your pimatic manually:
`DEBUG=ssdp-server node pimatic.js` 
Then you should see the debug output of the library that handles the discovery.

**Comment by n3roGit** [comment]
okay one second :)

**Comment by n3roGit** [comment]
ssdp-server using ip address: 192.168.1.13 +0ms
  ssdp-server binding to port 1900 for ssdp discovery +16ms
18:16:59.772 [pimatic] rule startup: set color #F5F5F5
18:16:59.776 [pimatic] rule startup: set color #F5F5F5
18:16:59.779 [pimatic] rule startup: set color #F5F5F5
  ssdp-server server error:
  ssdp-server Error: bind EADDRINUSE 0.0.0.0:1900
  ssdp-server     at Object.exports._errnoException (util.js:873:11)
  ssdp-server     at exports._exceptionWithHostPort (util.js:896:20)
  ssdp-server     at dgram.js:214:18
  ssdp-server     at nextTickCallbackWith3Args (node.js:453:9)
  ssdp-server     at process._tickDomainCallback (node.js:400:17) +4s
18:17:00.977 [pimatic-ping] Error on ip lookup of zbox.fritz.box: Error: queryA ENOTFOUND zbox.fritz.box
18:17:01.155 [pimatic-fritz] Re-establishing session at http://fritz.box
  ssdp-server Setup Server running. +828ms

**Comment by michbeck100** [comment]
looks like there is already running on port 1900. Do you have other Amazon echo bridges like the ha-bridge running?

**Comment by n3roGit** [comment]
found the problem. habridge and minidlna locked the port. now it works :)

uncompfortably i cant change the minidlna port :( but your plugin works! =)

**Comment by michbeck100** [comment]
Good, i will see if i can make the port configurable

**Comment by michbeck100** [comment]
@philicibine just for the record, it seems you can't use alexapi to control your devices. this is a feature only for real echos. Sorry
