### ISSUE TITLE
Feature Request: pimatic-raspbee support

### ISSUE THREAD

**Issue by smarthomeagentur** [michbeck100/pimatic-echo#70]
Hi,
I would like to ask if it is possible to implement lights and devices from the pimatic-raspbee plugin . The ConBee zigbee stick is one of the best solutions to control many zigbee devices and to share them over echo would be great.

**Comment by michbeck100** [comment]
`RaspBeeSwitch` should work OOB as it has not special template. `RaspBeeCT` and `RaspBeeDimmer` have their own templates: 'raspbee-ct' and 'raspbee-dimmer' (see https://github.com/treban/pimatic-raspbee/blob/master/raspbee.coffee#L977). These templates must be added to the list of supported devices here: https://github.com/michbeck100/pimatic-echo/blob/master/lib/hue.coffee#L18 
You could first try to add them manually and check if they work OOB. If they do just create a pull request

**Comment by smarthomeagentur** [comment]
Hi @michbeck100 ,
thanks for the info. I found the array and have it running with the templates. For me (Ikea Tradfri lights with raspbee) it works perfect OOB. I made a pull request for this but I don´t have other devices to test with.
