### ISSUE TITLE
After reboot device not found 

### ISSUE THREAD

**Issue by heiko1988** [michbeck100/pimatic-echo#75]
Hi,

I have a raspberry 4 with buster image. 

The pimatic echo plugin work normally. 
Can device turn on and off
After 
When I reboot the pi the pimatic do not found echo devices in configuration. 

Error log
error [pimatic]: Invalid config of device "heizung-steuerung": Property "echo" is not a valid property

Say by every device 

And I can not switch any devices 

Wenn I stop pimatic manuely and start manually. Then works all fine and I can normally switch the devices 

Regards heiko

**Comment by michbeck100** [comment]
Please make sure that pimatic-echo is the first plugin in the list in your config.json

**Comment by heiko1988** [comment]
Hi,

The echo plugin is the first plugin. 


I have this problems only after pi reboot and pimatic automatically start. 

When I stop pimatic over the console and start again manuely then works. This problem I have only with the pi 4 and buster image. 

When I use the same pimatic config on the pi 3 with stretch image, then works all perfectly.

**Comment by michbeck100** [comment]
Haven't tried the buster image yet. Does the plugin load properly during startup? If the plugin crashed you will see the same messages

**Comment by heiko1988** [comment]
Jetzt mal deutsch ;) 

Macht es einen Unterschied ob pimatic automatisch gestartet wird oder manuell über Console? 

Gibt es einen log wo ich es nachvollziehen kann ob das plugin abgestürzt ist?

**Comment by michbeck100** [comment]
Das sollte auf jeden Fall im Log von pimatic stehen. `pimatic-daemon.log` wenn automatisch gestartet.

**Comment by michbeck100** [comment]
Die Meldung `Property "echo" is not a valid property` deutet auf jeden Fall darauf hin, dass das Plugin nicht gestartet ist

**Comment by michbeck100** [comment]
Any updates?

**Comment by edautz** [comment]
I got a simular problem, after power failure, my echo didn’t work anymore with Pimatic-echo. After deleting all the devices in the Alexa app, things get worse. The devices couldn’t get discovered anymore. 

I tried all kinds of solutions, but it seems that the discovery protocol of the Echo isn’t compatible anymore with Pimatic-echo.

Now I am making another solution with an ESP8266 and this software:

https://github.com/vintlabs/fauxmoESP

First tries are promising. The configured devices in the ESP are instantly discovered by the Echo. I am going to extend the code with OTA, a webserver and a Pimatic integration through the Pimatic rest API.

Not so easy and userfriendly as Pimatic-echo, but I love the Echo voice intergration to Pimatic.
I used Pimatic-echo for several years, and until now it worked very well. For that I want to @michbeck100 thank very much, but I want a working setup again.

**Comment by michbeck100** [comment]
Be aware that most of the projects have similar issues. For fauxmoESP see https://github.com/vintlabs/fauxmoESP/issues/166. But they seem to have found a solution. I will try to implement this myself. The only downside with this is, that everyone must probably reset the device list at alexa.amazon.com. And with the next update of the echo devices this could be broken again.

**Comment by edautz** [comment]
@michbeck100, if you could modify your code, that would be great. 

I am aware that it could be a tempory solution. But if we can used that for a few years, that is ok. 

We have to deal with this kind of issues, until a true nicely designed opensource smart speaker is available.

**Comment by michbeck100** [comment]
Seems that 5fe77d8fcd36e11ba8c1692479fc5d9302f63f49 did the trick. It’s never been so stable for me. So I’m closing this issue. Please reopen if you still have issues.
