### ISSUE TITLE
Pimatic-echo 0.5.6 Find only first Device in a Buttons Device

### ISSUE THREAD

**Issue by heiko1988** [michbeck100/pimatic-echo#76]
Hi,

Pimatic-echo 0.5.6 Find only first Device in a Buttons Device.
Regards

**Comment by michbeck100** [comment]
Any errors in the logs? Are you using the core ButtonsDevice?

**Comment by heiko1988** [comment]
No errors in the log.

A only the last device found in the buttons device. 

![Screenshot_20200208-150910_Chrome Beta](https://user-images.githubusercontent.com/5456599/74086642-0b5d6f80-4a85-11ea-91db-5f4c32c77d35.jpg)

**Comment by michbeck100** [comment]
Found the error at https://github.com/michbeck100/pimatic-echo/blob/master/lib/hue.coffee#L58. Now i only need to find the time to fix this.

**Comment by michbeck100** [comment]
Please try with version 0.5.8. Should be fixed now. Unfortunately you have to remove all previous devices again.
