### ISSUE TITLE
An uncaught exception occurred: TypeError: this is not a typed array.

### ISSUE THREAD

**Issue by MMore** [michbeck100/pimatic-echo#77]
The `pimatic-echo` plugin worked for me for several months. Unfortunately I need to readd my Alexa devices after I changed some structural things. At the same time I updated pimatic (to 0.9.54) + all plugins including `pimatic-echo` (to 0.5.8). I am still using node 4.4.5.

So I went into the Discover Devices mode of pimatic and said to Alexa to search for new devices. The result is that I see many of the following exceptions in the pimatic log. Moreover no device is found.
I've already deleted the `echo-database` folder. 

> 08:28:26.738 [pimatic] error: An uncaught exception occurred: TypeError: this is not a typed array.
08:28:26.738 [pimatic] error:>    at Function.from (native)
08:28:26.738 [pimatic] error:>    at UpnpServer._getDiscoveryResponses (/opt/pimatic-app/node_modules/pimatic-echo/lib/upnp.coffee:54:29)
08:28:26.738 [pimatic] error:>    at Socket.<anonymous> (/opt/pimatic-app/node_modules/pimatic-echo/lib/upnp.coffee:22:14)
08:28:26.738 [pimatic] error:>    at emitTwo (events.js:87:13)
08:28:26.738 [pimatic] error:>    at Socket.emit (events.js:172:7)
08:28:26.738 [pimatic] error:>    at UDP.onMessage (dgram.js:480:8)
08:28:26.738 [pimatic] error:> This is most probably a bug in pimatic or in a module, please report it!
08:28:26.753 [pimatic] warn: Keeping pimatic alive, but could be in an undefined state, please restart pimatic as soon as possible!
08:28:26.766 [pimatic-echo] debug: << server got: M-SEARCH * HTTP/1.1
08:28:26.766 [pimatic-echo] debug:>Host: 239.255.255.250:1900
08:28:26.766 [pimatic-echo] debug:>Man: "ssdp:discover"
08:28:26.766 [pimatic-echo] debug:>MX: 3
08:28:26.766 [pimatic-echo] debug:>ST: upnp:rootdevice
08:28:26.766 [pimatic-echo] debug:>
08:28:26.766 [pimatic-echo] debug:> from 192.168.178.25:50000
08:28:26.811 [pimatic] error: An uncaught exception occurred: TypeError: this is not a typed array.
08:28:26.811 [pimatic] error:>    at Function.from (native)
08:28:26.811 [pimatic] error:>    at UpnpServer._getDiscoveryResponses (/opt/pimatic-app/node_modules/pimatic-echo/lib/upnp.coffee:54:29)
08:28:26.811 [pimatic] error:>    at Socket.<anonymous> (/opt/pimatic-app/node_modules/pimatic-echo/lib/upnp.coffee:22:14)
08:28:26.811 [pimatic] error:>    at emitTwo (events.js:87:13)
08:28:26.811 [pimatic] error:>    at Socket.emit (events.js:172:7)
08:28:26.811 [pimatic] error:>    at UDP.onMessage (dgram.js:480:8)
08:28:26.811 [pimatic] error:> This is most probably a bug in pimatic or in a module, please report it!
08:28:26.825 [pimatic] warn: Keeping pimatic alive, but could be in an undefined state, please restart pimatic as soon as possible!

In #68 I saw same issues which were resolved by reinstalling pimatic. So I will remove the `node_modules` folder an reinstall. Any other ideas?

**Comment by michbeck100** [comment]
This is because Buffer.from was introduced with node 6: https://stackoverflow.com/questions/36899888/getting-typeerror-this-is-not-a-typed-array-using-buffer-from-in-mocha

Do you have any chance to update to node >= 6?

**Comment by MMore** [comment]
I updated to a newer node version and it works now. Thank you.
