### ISSUE TITLE
After Update to 5.9 - Every ~ 10 Seconds Warning "Deivce with X ID not found"

### ISSUE THREAD

**Issue by tehmilcho** [michbeck100/pimatic-echo#78]
Hey,

i updated now the Plugin but now i get every ~ 10s Warnings im Pimatic

![image](https://user-images.githubusercontent.com/22918349/83396894-f96d5700-a3fc-11ea-9aba-fb78bcce4362.png)

I already delete all devices from "alexa.amazon.com" and start a new inclusion over Pimatic -> Find Devices and alexa.amazon.com.

Is there something that i missed to clean?

**Comment by tehmilcho** [comment]
And i have still all the devices twice on "alexa.amazon.com" foreach i got a "Royal Philips Electronics"-Device and a "Dimmable Light" =/

**Comment by michbeck100** [comment]
The update changed the way the ids for all devices are generated. This is why you have to remove all devices from alexa.amazon.com. If you don’t remove it, alexa still uses the old ids, and pimatic-echo logs this, because it can’t find the id. I’ve made the experience that you might have to remove every devices by its own. The “remove all” button might not work.

**Comment by tehmilcho** [comment]
i tried already:

1.
- Shutdown alle Echos and delete all the devices from "alexa.amazon" -> Without Sucess

2.
- Searched only with my Gen1 - Amazon Echo (the frist big speaker thing) i foudn only "dimmable lights"
- deleted every "dimmable lights" one by one -> Alexa cant control the Devices anymore

at the moment i just have all the device twice and it works but everytime alexa (i think) checks for the "dimmable lights" its push out the Warning.

**Comment by michbeck100** [comment]
Did you remove the echo-database file? This has to be done, too, when removing all devices.

**Comment by tehmilcho** [comment]
no i dont.. should this not recreated when i start the over Pimatic "search devices"?

**Comment by michbeck100** [comment]
Actually you are right. I'm not sure how this is implemented on the echo side. The echoUsers file contains a list of known users. Maybe the echo still "reuses" the old devices when the user is already known. Only if you delete the files you can be sure that everything is removed.

**Comment by tehmilcho** [comment]
I think its related to my old "Echo". 

![image](https://user-images.githubusercontent.com/22918349/83534272-edfb5800-a4f0-11ea-9354-45eded2c4c0b.png)

Because as i sad if i turn every Echo off (Remove Power), clean all the devices, waited 5min and searched again i found only my Devices from the Iobroker IOT Skill so far so good. But i then poweron this old "echo" i found only the Iobroker Skill devices and all my devices as "dimmable lights" so i think its related to this old devices. 

Do you know if the "Echo Studio" will work with the Plugin? Because this should be my replacement for the old "echo".

**Comment by michbeck100** [comment]
Di you use the "remove all" feature from alexa.amazon.com? Please remove every single device by its own instead. I don't know if the Echo Studio works. Maybe anyone on the pimatic forum uses it, too? But I would reckon it works.

**Comment by tehmilcho** [comment]
yep i used most "Delete all".. mhh anyway .. its works now .. and the celeron of my lattepanda seems not infected by the warnings (still 0-1% CPU) so .. maybe we just close it.

**Comment by tehmilcho** [comment]
Just if anyone has the same.. @michbeck100  wars right.. you have to delete every Device one by one over the Alexa App on your Phone / Tablett /etc ... then the Warnings are gone and all works fine.

You still see over the Alexa website the devices twice but it seems that that doesn't matter.
