### ISSUE TITLE
Strange behavior since a few days

### ISSUE THREAD

**Issue by tehmilcho** [michbeck100/pimatic-echo#80]
hey,

i have had some strange errors recently. 

For Example:
- Alexa says "device /group not responding" 
- Alexa says "ok" but nothing happend

i  restart alexa without success, the only thing that helps is to restart Pimatic. i have not changed my devices or configuration for months. 

Is there some new Update from the Alexa-Site that makes this strange problems? 
Has somebody else this Problems?

**Comment by michbeck100** [comment]
No, I haven't seen this behavior yet.

**Comment by michbeck100** [comment]
Do you still have these problems?

**Comment by tehmilcho** [comment]
Hey,

nope i dont have it again .. but I am currently now also moving device by device to Iobroker Alexa Skill.
