### ISSUE TITLE
devices trigger other devices, no more devices found by alexa

### ISSUE THREAD

**Issue by betz0r** [michbeck100/pimatic-echo#81]
Hi there,

i used pimatic-echo with my echo dot successfully the last two years.
Suddenly after a restart of pimatic due to updates a month ago, when i used alexa to turn on/off devices by their name, a different device was switched on/off, not the called one. (felt like it was shifted by one element in the devices list/array, but was unreproducable).

Then i removed all the devices from alexa, started disovery again (pimatic then alexa) but no more devices are found

No matter what i do, restart pimatic, restart echo dot, restart rasperrypi3 (pimatic host), all in different sequences, no more devices of pimatic are found.

I have one smartplug outside of pimatic (non philips hue) which works great and is also instantly found by alexa when deleted and discovered again. So i can exclude my echo dot as a source of this problem.

Parts of the config:
```
"plugins": [
    {
      "address": "192.168.1.192",
      "comfyTemp": 21,
      "ecoTemp": 19,
      "plugin": "echo",
      "active": true,
      "port": 80,
      "debug": true
    },
    {
      "plugin": "cron"
    },
    ...
```

And my devices look like this:

```
    ...
    {
      "protocols": [
        {
          ...
        }
      ],
      "xOnLabel": "An",
      "xOffLabel": "Aus",
      "id": "elro-AB",
      "name": "Lampe Küche",
      "class": "HomeduinoRFSwitch",
      "echo": {
        "name": "Kueche",
        "additionalNames": [
          "Kitchen",
          "Kuechenzeile"
        ],
        "active": true
      }
    },
    ...
```

My pimatic-daemon.log display in debug mode the following:
[https://pastebin.com/bTUYaSsK](https://pastebin.com/bTUYaSsK)

Alexa does not find any new devices. 

Anyone else experiencing this issue since beginning of november?

How can i debug this issue further?

**Comment by michbeck100** [comment]
Please make sure to delete the echo-database folder from your pimatic root. Then  try to search for devices again. The last update changed the way the devices are identified to make sure you can move or delete devices from pimatic

**Comment by betz0r** [comment]
Thanks for the ultra fast response. 
I stopped pimatic, deleted the folder in its root directory and started it again, sadly still no devices are discovered.

Any further hints what i could check?

**Comment by michbeck100** [comment]
Not at the moment. I will check if I have the same problem

**Comment by betz0r** [comment]
Today I scanned again without changing anything and all devices were found and work without issues. Will report if the incorrect links of devices will happen again.

**Comment by betz0r** [comment]
After losing all links between Alexa devices and pimatic devices (pimatic responded with "<ID> not found" when using alexa to control pimatic devices), i tried to scan for devices again.
Now Alexa does not find any devices anymore.
Deleting "echo-database" directory and nodemodule/pimatic-echo did not help.

Did another change of protocol happen on the alexa side? On the pimatic side nothing changed, all up2date and working.

**Comment by michbeck100** [comment]
There must be a change on the Alexa side obviously. But I can't tell which, as I am not working for amazon ;-)

**Comment by michbeck100** [comment]
As this can happen every time and I can't do much about it, I close this ticket.
